### ISSUE TITLE
Remove obsolete content

### ISSUE THREAD

**Issue by alexandr-sizov** [metrostroi-repo/MetrostroiAddon#102]

**Comment by glebqip** [comment]
https://github.com/metrostroi-repo/MetrostroiAddon/blob/dev/lua/metrostroi/sv_socket.lua
https://raw.githubusercontent.com/metrostroi-repo/MetrostroiAddon/dev/lua/metrostroi/sv_socket.lua

**Comment by glebqip** [comment]
https://github.com/metrostroi-repo/MetrostroiAddon/blob/c145c65465a0946b2213b831bac3a7d7334337a2/lua/metrostroi/sv_socket.lua
https://github.com/metrostroi-repo/MetrostroiAddon/blob/c145c65465a0946b2213b831bac3a7d7334337a2/lua/metrostroi/sv_centralisation.lua
https://github.com/metrostroi-repo/MetrostroiAddon/blob/c145c65465a0946b2213b831bac3a7d7334337a2/lua/metrostroi/sh_arm.lua
https://github.com/metrostroi-repo/MetrostroiAddon/tree/c145c65465a0946b2213b831bac3a7d7334337a2/lua/metrostroi/_obsolete
https://github.com/metrostroi-repo/MetrostroiAddon/tree/c145c65465a0946b2213b831bac3a7d7334337a2/lua/entities/_obsolete
https://github.com/metrostroi-repo/MetrostroiAddon/tree/c145c65465a0946b2213b831bac3a7d7334337a2/lua/entities/gmod_track_arm
https://github.com/metrostroi-repo/MetrostroiAddon/tree/c145c65465a0946b2213b831bac3a7d7334337a2/lua/entities/gmod_train_sound_provider
https://github.com/metrostroi-repo/MetrostroiAddon/tree/c145c65465a0946b2213b831bac3a7d7334337a2/lua/entities/gmod_train_door
https://github.com/metrostroi-repo/MetrostroiAddon/tree/c145c65465a0946b2213b831bac3a7d7334337a2/lua/entities/gmod_subway_81-7036
https://github.com/metrostroi-repo/MetrostroiAddon/tree/c145c65465a0946b2213b831bac3a7d7334337a2/lua/entities/gmod_subway_81-7037

**Comment by cyber-dream** [comment]
![image](https://user-images.githubusercontent.com/3523514/104072604-abcf8d00-521c-11eb-8c96-589c5fa10e10.png)

**Comment by glebqip** [comment]
![image](https://user-images.githubusercontent.com/6125008/104072669-dd485880-521c-11eb-9ef9-c4a127bed946.png)

**Comment by glebqip** [comment]
https://github.com/metrostroi-repo/MetrostroiAddon/tree/3b612d69f284d99196423067f31ef5806ec54d06/lua/metrostroi/systems/_obsolete
https://github.com/metrostroi-repo/MetrostroiAddon/tree/3b612d69f284d99196423067f31ef5806ec54d06/lua/metrostroi_data/languages_
