### ISSUE TITLE
Не работает клиентский дебаг сигналки

### ISSUE THREAD

**Issue by alexandr-sizov** [metrostroi-repo/MetrostroiAddon#108]

**Comment by TheFUlDeep** [comment]
Работает жеж. Там единственное, есть прикол, если ты на клиенте включаешь дебаг и далеко отлетаешь от места, где ты его включил, таблички с информацией не появятся. Но ты просто заново дергаешь галочку дебага и все снова появляется.

**Comment by alexandr-sizov** [comment]
> Работает жеж. Там единственное, есть прикол, если ты на клиенте включаешь дебаг и далеко отлетаешь от места, где ты его включил, таблички с информацией не появятся. Но ты просто заново дергаешь галочку дебага и все снова появляется. Можно тупо костыль сделать, чтобы галка сама каждые пару секунд передергивалась и все xD

не работает, версия обычная, не хромиум

**Comment by alexandr-sizov** [comment]
![image](https://user-images.githubusercontent.com/31768135/113470350-9655b200-945d-11eb-83e1-1a1a82c71adc.png)
![image](https://user-images.githubusercontent.com/31768135/113470355-9a81cf80-945d-11eb-8f4e-fa2e831a7e93.png)

1. value в цикле  "ent" а общаемся к sig - косяк
2. с исправленным п.1, лично у меня без использования bDrawingDepth в условии все начинает рисоваться, с ним - не хочет

![image](https://user-images.githubusercontent.com/31768135/113470406-0a905580-945e-11eb-994f-1786270bd09a.png)

**Comment by alexandr-sizov** [comment]
@TheFUlDeep

**Comment by TheFUlDeep** [comment]
> value в цикле "ent" а общаемся к sig - косяк

Все же там нормально. Мне кажется, ты не в ту версию файла смотришь https://github.com/metrostroi-repo/MetrostroiAddon/blob/dev/lua/entities/gmod_track_signal/cl_init.lua#L593

**Comment by alexandr-sizov** [comment]
Да, не ту...
