### ISSUE TITLE
Решить, где храним модели и ведем по ним таски

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#118]

**Comment by cyber-dream** [comment]
Давайте тут решим, как поступим. "Исходники" разумеется на гите не будут размещаться. 

Я не вижу проблемы в этом же репозитории хостить и mdl с материалами.

**Comment by glebqip** [comment]
Аналогично

**Comment by CrIcKeT98** [comment]
Контент залит.

**Comment by old702** [comment]
Удалил контент, в который позже были внесены изменения. Пока что удален 81-701.

**Comment by cyber-dream** [comment]
Контент переведён на lfs
