### ISSUE TITLE
Старая Игла: убрать кнопки "вниз", "вверх"

### ISSUE THREAD

**Issue by toxin1pilot** [metrostroi-repo/MetrostroiAddon#123]
Кнопки у иглы старого образца (с зелёным дисплеем) только нажимаются, они не имеют возможности наклона и управления таким образом

Источник - блок старой иглы у меня на балконе

**Comment by glebqip** [comment]
Необходима ещё инфа по работе этой иглы тогда, учитывая что кнопки только две

**Comment by toxin1pilot** [comment]
Если удастся запустить по питанию, попробую собрать необходимую инфу

**Comment by old702** [comment]
Собственно две кнопки это тупо две кнопки, они ни вверх, ни вниз не могут, просто нажимаются
toxin1pilot — 03/21/2021
Без ПЦБК она при нажатии на правую кнопку вываливается в перезагрузку
По левой кнопке листается меню
В порядке от самого последнего до самого первого

**Comment by CrIcKeT98** [comment]
Игла обновлена в #94
