### ISSUE TITLE
Е (81-703): Питерский промежуток

### ISSUE THREAD

**Issue by MrSandManFM** [metrostroi-repo/MetrostroiAddon#125]
Вагоны, которые спавнятся вместе с Ем (по галке в спавнере) координально отличаются от того, что можно было увидеть в поздних годах существования Е. Учитывая, что сами Емы в их позднем исполнении, Ешки должны тоже быть поздними.

Вагон Е, 2016г.:
![image](https://user-images.githubusercontent.com/4011223/107228077-46dea100-6a2d-11eb-9b6b-225a5a7c13cf.png)

Вагон Е, метрострой: 
![image](https://user-images.githubusercontent.com/4011223/107228131-5b229e00-6a2d-11eb-8c94-b576828a2f2c.png)

Что нужно изменить:

- [ ] 1. Сидения: в поздних Е их заменили на жесткие, идентичные в вагонам Ем.
![image](https://user-images.githubusercontent.com/4011223/107230593-527f9700-6a30-11eb-8c2a-cdd312ba419f.png)
- [ ] 2. Наклейки на дверях и на окнах. "Не прислонятся" и "Места для ..." нужно привести, вероятно, либо к современным исполнениям, либо к предыдущим современным. На фотографии 2016г. как раз предыдущие, в то время как в Еме в метрострое современный вариант, но только "Не прислонятся": "Места для ..." совсем старые, советские. Что тоже, естественно, неверно. Таск можно накинуть мне, наклейка в Еме моя.
- [ ] 3. Линкруст. В метрострое он не закрашен, в реальном же исполнении на нем миллион слоев краски.
- [ ] 4. Связь пассажир-машинист, просто поменять.
- [ ] 5. Вероятно добавить питерскую мишуру. Схемы, рамки для рекламы.
- [ ] 6. Цвет пола. В метрострое, кажется, через чур красный.
- [ ] 7. Материал Дерева. В метрострое абсолютно не похоже на дерево в целом, не говоря о сходстве с реальным образцом.
- [ ] 8. Сделать варианты кузова без фар. Часто бывает, что нет как минимум красных и ВУС, а иногда бывает и нет основых.
- [ ] 10. Добавить бортовые лампы.
![image](https://user-images.githubusercontent.com/4011223/107230816-95da0580-6a30-11eb-8eb9-79bcd25f7305.png)
- [ ] 9. Также вероятно стоит перекрасить кабину: чаще всего она в позднее время была бежевой, оконные рамы были деревянные (а не железные, как в метрострое). Также в метрострое линкруст не закрашен (как и в салоне) хотя в реальности он был закрашен примерно всегда.
 ![image](https://user-images.githubusercontent.com/4011223/107230002-902ff000-6a2f-11eb-8483-3f52b9b8291c.png)
![image](https://user-images.githubusercontent.com/4011223/107230518-3bd94000-6a30-11eb-8981-b2bcd9b05c91.png)
![image](https://user-images.githubusercontent.com/4011223/107230922-bb670f00-6a30-11eb-8a1d-b90ce597efc5.png)
- [ ] 11. Заменить двери на аналогичные Ем.
- [ ] 12. Пофиксить общие косяки Е из отдельного таска.

**Comment by MrSandManFM** [comment]
![image](https://user-images.githubusercontent.com/4011223/107368985-41975a00-6af2-11eb-9618-e132f482063a.png)
Задизайнил оставшуюся наклейку для 2 пункта

Имеет ли смысл делать старые наклейки? Тогда придется делать их выбираемость, или можно будет сделать их зависимость от выбранной линии (на старой НВЛ, например, старые наклейки, что будет довольно аутентично)
@glebqip 
![image](https://user-images.githubusercontent.com/4011223/107369119-6be91780-6af2-11eb-8a17-6f1a51898a94.png)

**Comment by glebqip** [comment]
По желанию, можно сделать единственную галку Old/New, которая может менять сразу несколько вещей. Можно и на тип поезда, НВЛ и КВЛ Old старые, КВЛ New новые. Самое главное не переборщить с количеством моделей и текстур
