### ISSUE TITLE
Е, Еж, Еж3: поломанная гофра 

### ISSUE THREAD

**Issue by MrSandManFM** [metrostroi-repo/MetrostroiAddon#126]
У всех Е* с двумя гофрами в районе 3-й двери сломана гофра:
![image](https://user-images.githubusercontent.com/4011223/107234790-13a01000-6a35-11eb-8c8f-c0104a6aa677.png)
![image](https://user-images.githubusercontent.com/4011223/107234848-26b2e000-6a35-11eb-9d39-976b12fbaa58.png)

**Comment by old702** [comment]
Проверить местоположение вершин этих гофр
