### ISSUE TITLE
Е (81-703): баги модели

### ISSUE THREAD

**Issue by MrSandManFM** [metrostroi-repo/MetrostroiAddon#127]
- [ ] **Шейдинг**
на каждом черпаке:
![image](https://user-images.githubusercontent.com/4011223/107233323-83150000-6a33-11eb-8093-9dd303c7aee0.png)
над каждой дверью:
![image](https://user-images.githubusercontent.com/4011223/107233345-8a3c0e00-6a33-11eb-85f7-9d35dc71ab59.png)
у последней двери:
![image](https://user-images.githubusercontent.com/4011223/107233366-9031ef00-6a33-11eb-9e39-c23d78f1a0fd.png)
![image](https://user-images.githubusercontent.com/4011223/107233553-c40d1480-6a33-11eb-9d44-398b67ecccdb.png)

- [ ] **На промежутке потеряны решетки в салоне:**
![image](https://user-images.githubusercontent.com/4011223/107233651-dab36b80-6a33-11eb-805b-c880d2ce5604.png)

- [ ]  **Очень много поехавшей развертки:**
![image](https://user-images.githubusercontent.com/4011223/107233738-f28aef80-6a33-11eb-91c6-9a6b8c50fbab.png)
![image](https://user-images.githubusercontent.com/4011223/107233753-f61e7680-6a33-11eb-9b13-5e7c35887671.png)
![image](https://user-images.githubusercontent.com/4011223/107233910-249c5180-6a34-11eb-9129-1328d735404c.png)
![image](https://user-images.githubusercontent.com/4011223/107234019-44337a00-6a34-11eb-8e21-44bd75b4f519.png)

- [ ] **Люки в салоне вероятно стоит чуть замоделить, выглядит оч плохо:**
![image](https://user-images.githubusercontent.com/4011223/107233861-164e3580-6a34-11eb-83bf-890e0c92c264.png)

- [ ] **Потолок, по идее, сегментированный (на фотках немного видно). В метрострое - нет.**

- [ ]  **Все тот же проеб гофры в районе третьей двери (#126):**
![image](https://user-images.githubusercontent.com/4011223/107234113-5dd4c180-6a34-11eb-9407-cb01c723dac3.png)

**Comment by old702** [comment]
Проверить положения вершин гофр

**Comment by cyber-dream** [comment]
@MrSandManFM нужна декомпозиция таска. Здесь чек-боксами или каждый своим таском - неважно

**Comment by MrSandManFM** [comment]
> @MrSandManFM нужна декомпозиция таска. Здесь чек-боксами или каждый своим таском - неважно

Ну я чекбоксы как в СПб Е сделаю тогда, так наверное логичнее будет?

**Comment by cyber-dream** [comment]
Да

**Comment by CrIcKeT98** [comment]
Шейдинг внешней модели и потолок поправлены
