### ISSUE TITLE
Артефакты на текстуре в кабине Е

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#136]
![IMG_20210213_110321_864.jpg](https://user-images.githubusercontent.com/3523514/107845502-ee245500-6dec-11eb-95cd-2a2bb04aa9ca.jpg)

**Comment by old702** [comment]
У тебя очень странный репорт о баге, даже мне не понятно что тут есть артефакт

**Comment by cyber-dream** [comment]
Из-за сжатия нормалки + возможно, растянутой юв решетка на решетку не похожа

**Comment by old702** [comment]
Скорее низкий тексель в этом месте просто...
