### ISSUE TITLE
Доработать Московскую версию 81-717/714

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#146]
![81-717 2 гофры ММЗ](https://user-images.githubusercontent.com/80965105/111789262-fe3ec100-88d1-11eb-96fd-29dffb3888d5.jpg)
![714 ЛВЗ](https://user-images.githubusercontent.com/80965105/111789323-0e56a080-88d2-11eb-94aa-8adf95695be1.jpg)
![714 МВМ](https://user-images.githubusercontent.com/80965105/111789330-10206400-88d2-11eb-8a8e-cc0243b96205.jpg)
![81-714 решётки](https://user-images.githubusercontent.com/80965105/111789362-1ca4bc80-88d2-11eb-9524-62370fab772b.jpg)

Добавить решётки ниже окон на вагонах, добавить кузов ММЗ с 2 гофрами и сделать разрыв между гофрами в конце корпуса вагона (это только на ММЗ/МВМ), также доработать 714 добавить капельник от ЛВЗ (водосток на крыше) + добавить горизонтальное расположение ламп бортовой сигнализации, всё это с кастомизацией в спавнере.

**Comment by glebqip** [comment]
Про бортовые есть в #66 . Там проблема в высоте окон. Для полноценного 717 стоит сделать подстекольную маску и вообще приближенные к 717 схемы

**Comment by Alexrig23** [comment]
> Про бортовые есть в #66 . Там проблема в высоте окон. Для полноценного 717 стоит сделать подстекольную маску и вообще приближенные к 717 схемы

а полноценный ММЗ/ЛВЗ 717 будет в обновлении в или нет?

**Comment by Alexrig23** [comment]
> Про бортовые есть в #66 . Там проблема в высоте окон. Для полноценного 717 стоит сделать подстекольную маску и вообще приближенные к 717 схемы

и да, дополняю ещё, кресты на дверях не стыкуются с полосой
![Снимок экрана (653)](https://user-images.githubusercontent.com/80965105/111863457-c89ae600-896c-11eb-934c-3b0778960e12.png)

**Comment by Alexrig23** [comment]
@cyber-dream @glebqip а вообще в обновлении Метростроя 2021 будут добавлены электросхемы от базовой модели 81-717/714 из ММЗ и ЛВЗ?

**Comment by Alexrig23** [comment]
просто ММЗ и ЛВЗ разные

**Comment by glebqip** [comment]
А можно увидеть эту разность и эти электросхемы  базовых версий 717 и 714 ММЗ и ЛВЗ?

**Comment by Alexrig23** [comment]
> А можно увидеть эту разность и эти электросхемы базовых версий 717 и 714 ММЗ и ЛВЗ?

опровергаю с их разностью, одинаковы.

**Comment by Alexrig23** [comment]
https://drive.google.com/drive/folders/1nSsch4fmnQEam0PUD66hpmB7HAs5ay7-?usp=sharing - модели 717 и 714 с 2 гофрами и обрывом между гофрами в конце корпуса вагона, также 717/714 МВМ(3 гофры) тоже с обрывами между гофрами в конце корпуса вагона, и модель 714 с капельницей от ЛВЗ, придётся делать скины под 2 гофры и под капельницу ЛВЗ для 714.
![Снимок экрана (1156)](https://user-images.githubusercontent.com/80965105/127447907-eb6ec150-da25-41d1-82d1-2f778b50613b.png)
![Снимок экрана (1150)](https://user-images.githubusercontent.com/80965105/127447918-6e7763f5-c847-46c8-a117-c8d4b5e5a7a0.png)
![Снимок экрана (1151)](https://user-images.githubusercontent.com/80965105/127447920-0847f3f8-a1c4-4ea5-83ad-6fdc8b35262a.png)
![Снимок экрана (1152)](https://user-images.githubusercontent.com/80965105/127447922-1a1f6de6-7f60-4c22-8c56-3b9d10ba8a3c.png)
![Снимок экрана (1153)](https://user-images.githubusercontent.com/80965105/127447923-23ff16f6-46ce-4f2e-b7e7-810a7662b378.png)
![Снимок экрана (1154)](https://user-images.githubusercontent.com/80965105/127447925-62848a05-08f9-478a-814f-a935bde1f11f.png)
![Снимок экрана (1155)](https://user-images.githubusercontent.com/80965105/127447926-6f70e15f-5fe3-404c-abaa-37dc805fa999.png)

**Comment by Alexrig23** [comment]
#313

**Comment by Alexrig23** [comment]
https://github.com/metrostroi-repo/MetrostroiAddon/issues/378
