### ISSUE TITLE
Добавить второй вариант тележки со шпинтовым надбуксовым подвешиванием для 81-717.5/714.5 и 5М (если будет конечно) и сделать полноценный рабочий ЭКК (Пальцевой и Штепсельный)

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#147]
![161300](https://user-images.githubusercontent.com/80965105/111790939-ca649b00-88d3-11eb-95b9-1f911da434ce.jpg)

Не помешало бы для кастомизации добавить тележку от модификации .5 и 5М со шпинтовым надбуксовым подвешиванием, вот шпинтовым и поводковым отличаются (так как в кастомизации есть модификация .5) + сделать два варианта рабочих ЭКК

![714_telega_1](https://user-images.githubusercontent.com/80965105/134793614-078803f6-a8e0-4276-b87f-83cb04a8d1ab.jpg)

![714_telega](https://user-images.githubusercontent.com/80965105/134793628-59e5d190-3fbd-4b54-bfa3-4b91321f8d98.jpg)
![130933360-127e7cfc-6e2d-42bc-8ab4-6bcd2ad0131f](https://user-images.githubusercontent.com/80965105/134793840-570baeb2-1001-47ad-bae8-a73bd5fc4838.png)
![image251](https://user-images.githubusercontent.com/80965105/111791671-7c9c6280-88d4-11eb-91c4-ff3e2d24562f.jpg)

https://zinref.ru/000_uchebniki/03410metro/003_00_00_vgoni_81_717_81_714_uchebnoe_posobie/005.htm

**Comment by cyber-dream** [comment]
Есть желающие помоделить экк? @metrostroi-repo/modellers

**Comment by Alexrig23** [comment]
> Есть желающие помоделить экк? @metrostroi-repo/modellers

а второй вариант тележки для .5 будет?

**Comment by toxin1pilot** [comment]
Помимо разноса ЭКК внешне (хотя сейчас даже крышка не открывается), потребуется дополнительно внести соответствующие изменения в схемы. А теперь самое главное - .5 от .0 отличается достаточно сильно, а по .0 информации по схемам куда меньше, получится очередная солянка, а не номерной, ИМХО

**Comment by Alexrig23** [comment]
@cyber-dream @toxin1pilot а улучшенный (второй) вариант тележки для .5 и 5М не планируется в обнове?
