### ISSUE TITLE
Добавить маску 1-4-1 для ЛВЗ 717 с значком "М" и чёрным бампером + добавить маску без значка "М" для МВМ/ЛВЗ вагонов

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#148]
![1030610](https://user-images.githubusercontent.com/80965105/111792759-9e4a1980-88d5-11eb-983c-9be01d8b733b.jpg)
![1344864](https://user-images.githubusercontent.com/80965105/111792764-9ee2b000-88d5-11eb-87c1-d0d22477a070.jpg)

**Comment by MrSandManFM** [comment]
Уже сделано на декомпиленной модели, @cyber-dream предлагаю переделать уже на исходниках

**Comment by MrSandManFM** [comment]
Аналогичная ситуация и с остальными масками, есть варианты с и без птички, тоже нужно на исходниках переделать

**Comment by cyber-dream** [comment]
Спасибо за предложение
