### ISSUE TITLE
Добавить эффект эхо чтобы было слышно как прибывает вдалеке поезд и уезжает со станции + сделать чтобы звуки из кабины машика, салона, снаружи звучали по разному.

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#152]
Извините что именно в багрепорт пишу я не знаю как перейти на тему про добавления нового контента, улучшить звуковые эффекты чтобы соотвествовали с реальностью, грохот колес на станции и т.д 

https://www.youtube.com/watch?v=pcTwGcQVyYc - пример отсюда

**Comment by glebqip** [comment]
Невозможно.
Звуковая система гмода не позволяет это сделать, а делать 4 копии файлов под каждый вариант это смерть
