### ISSUE TITLE
ПА-М АТП на 81-722

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#153]

**Comment by glebqip** [comment]
Что по поводу инфы?

**Comment by fixinit75** [comment]
РЭ есть на нее

**Comment by fixinit75** [comment]
[421427.078_-.pdf](https://github.com/metrostroi-repo/MetrostroiAddon/files/6181199/421427.078_-.pdf)

**Comment by fixinit75** [comment]
На всякий случай, ТЗ кину на модернизацию 722.1. Там могут быть некоторые вещи, которых нет в РЭ

[ТЗ.pdf](https://github.com/metrostroi-repo/MetrostroiAddon/files/6183054/default.pdf)

**Comment by alexandr-sizov** [comment]
Нет на синем юбике
