### ISSUE TITLE
Добавить КВР вариант салона и кабины для Ема-502/Ем-501 и 81-717/714

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#155]
![81-501М-502М_Пассажирский_салон_1](https://user-images.githubusercontent.com/80965105/112144077-c85b4e80-8be9-11eb-988a-cd77e6444f81.jpg)
![ema502m5](https://user-images.githubusercontent.com/80965105/112144082-c98c7b80-8be9-11eb-8e0c-2ff8ef745efd.jpg)
![718164](https://user-images.githubusercontent.com/80965105/112144087-cabda880-8be9-11eb-8423-8814bea169ce.jpg)
![1191469](https://user-images.githubusercontent.com/80965105/112144094-cd200280-8be9-11eb-9166-15613c3565d8.jpg)
![IMG_2255_sss_1200](https://user-images.githubusercontent.com/80965105/112144283-0c4e5380-8bea-11eb-8225-ae0cd73d9aa6.jpg)

**Comment by glebqip** [comment]
А электрические схемы КВР варианта Емы есть?

**Comment by Alexrig23** [comment]
> А электрические схемы КВР варианта Емы есть?

хз, в инете чет нету...

**Comment by kirieshka-spb** [comment]
> 
> 
> А электрические схемы КВР варианта Емы есть?

есть
