### ISSUE TITLE
Исправьте косяки (полигоны) с мордой у Еж3/Ем-508Т, Еж/Еж1

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#156]
видно на глазах полигоны у Еж3 и Ем-508Т, Еж/Еж1, а у Ема-502 и "Е" всё нормально.
![Снимок экрана (665)](https://user-images.githubusercontent.com/80965105/112160825-9b179c00-8bfb-11eb-8a19-384de59bbeac.png)
![Снимок экрана (668)](https://user-images.githubusercontent.com/80965105/112160826-9c48c900-8bfb-11eb-9c21-9b8f8cd34186.png)
![Снимок экрана (666)](https://user-images.githubusercontent.com/80965105/112160832-9d79f600-8bfb-11eb-8074-9da1c6a7d0f9.png)
![Снимок экрана (667)](https://user-images.githubusercontent.com/80965105/112160838-9eab2300-8bfb-11eb-8261-6069f8306e1f.png)

**Comment by glebqip** [comment]
#113
