### ISSUE TITLE
Переводы в signalling/switch tool

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#157]

**Comment by alexandr-sizov** [comment]
#107

**Comment by alexandr-sizov** [comment]
Есть ли смысл?

**Comment by fixinit75** [comment]
Как минимум, будет легче соображать тем, кто не сильно шарит в работе с сигналкой в метрострое. Не все же знают английский, да и он там тоже кривоватый.
