### ISSUE TITLE
81-717/540 СПБ: БАРС

### ISSUE THREAD

**Issue by kirieshka-spb** [metrostroi-repo/MetrostroiAddon#159]
При смене показания АЛС с разрешающего на 0, при Vф=0, происходит сработка АРС с последующей сработкой ЭПК.

**Comment by alexandr-sizov** [comment]
Как вариант замедлить self.RNT в БАРС
@glebqip 
        
        old:
        self.RNT =  (self.BR1 or self.BR2) or self.RNT and (self.KSR or KRT and (not self.RUVD or self.R2O))
        
        new:
        local RNT = (self.BR1 or self.BR2) or self.RNT and (self.KSR or KRT and (not self.RUVD or self.R2O))

        if RNT then
            self.RNT = true
            self.RNTTimer = false
        elseif not self.RNTTimer then
            self.RNTTimer = CurTime()+0.5
        elseif self.RNTTimer and CurTime() > self.RNTTimer then
            self.RNT = false
            self.RNTTimer = false
        end
