### ISSUE TITLE
Звук отпуска тормозов, индикатор ускорения в 81-720

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#160]
На головах нет звука отпуска тормозов, т.к не не задан звук release в cl_init + нет там и dPdT, ReleasedPdT там же. Индикатор ускорения не работает по приблизительно аналогичной причине.

**Comment by TheFUlDeep** [comment]
А у меня на dev ветке работает индикатор ускорения
![image](https://user-images.githubusercontent.com/39480610/115111353-a6ef4780-9f88-11eb-985c-77e63c489c95.png)
И звуки отпуска есть.

А вот что меня беспокоит, так это данная вейп машина на яузе. Просто запускаю, начинаю ехать - происходит вот такая штука. Ветка dev.
![image](https://user-images.githubusercontent.com/39480610/115111370-be2e3500-9f88-11eb-9ce2-525ca184d001.png)

**Comment by cyber-dream** [comment]
Pizda poezdu

**Comment by TheFUlDeep** [comment]
Возможно я какое-то обновление себе не замержил, конечно, сейчас потыкаюсь и отпишусь

**Comment by TheFUlDeep** [comment]
Нет, у меня последняя версия, значит реально проблема такая
![image](https://user-images.githubusercontent.com/39480610/115111549-8b387100-9f89-11eb-9d37-6b4384a0686b.png)

**Comment by TheFUlDeep** [comment]
С остальными паравозами такого "дыма" нет

**Comment by fixinit75** [comment]
Сейчас тестировал, не нашел такого бага, а вот полоска ускорения меня смущает. Дергается постоянно, да еще и на выбеге отображает ускорение.

**Comment by glebqip** [comment]
> Дергается постоянно, да еще и на выбеге отображает ускорение.
Она отображает реальное ускорение поезда, которое довольно шумное из-за угловатой коллизии рельс и в целом очень неточной физики.
Вопрос только про выбег, оно положительное? Если отрицательное, то вполне ок. В метрострое сильное трение из-за особенности физики

**Comment by fixinit75** [comment]
Сейчас видео запишу

**Comment by fixinit75** [comment]
Да не, даже смысла записывать нет, все норм, отрицательное, там, где надо, положительное на уклонах.

**Comment by TheFUlDeep** [comment]
> Она отображает реальное ускорение поезда, которое довольно шумное из-за угловатой коллизии рельс и в целом очень неточной физики.

А нельзя как-нибудь "сгладить" это? Например, самый глупый вариант - брать среде значение из соседних

**Comment by glebqip** [comment]
Тогда будет очень заметно это сглаживание наверное, т.е. очень долго будет пропадать например в 0

**Comment by fixinit75** [comment]
Кажется, вопрос исчерпан. Стоит закрывать?
