### ISSUE TITLE
Положение тележек 81-720

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#161]
Посмотрите, они частично появляются в салоне
![image](https://user-images.githubusercontent.com/78933401/114208742-7e52c680-9966-11eb-9c40-007f7605dbd9.png)
![image](https://user-images.githubusercontent.com/78933401/114208789-8d397900-9966-11eb-98f7-3bf77bde8769.png)

**Comment by TheFUlDeep** [comment]
Получается, из достаточно просто немного опустить относительно кузова?

**Comment by fixinit75** [comment]
Ну или кузов чуть приподнять. Кстати, на 1-м скрине беды с текстурой видно, прозрачная полоса.

**Comment by TheFUlDeep** [comment]
Еще вот такой прекол при повороте
![image](https://user-images.githubusercontent.com/39480610/115110587-d603ba00-9f84-11eb-878a-1a62f86fc7e9.png)

**Comment by TheFUlDeep** [comment]
Во. Все изменения в одном последнем коммите. И для 720 и для 721

**Comment by fixinit75** [comment]
Закрываем?

**Comment by TheFUlDeep** [comment]
Глеб закроет, когда пулл реквест увидит
