### ISSUE TITLE
Маска 2-2, 81-717 МСК, поручни на ней

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#163]
![image](https://user-images.githubusercontent.com/78933401/114323915-1cde5380-9b30-11eb-9087-a901d09c598b.png)
без комментариев

**Comment by glebqip** [comment]
А можно всё же с комментарием?

**Comment by fixinit75** [comment]
Удивительно, что ты не заметил, Глеб, о чем я говорю. Смотри, дырки на маске смещены относительно поручней на охренеть, какое расстояние. Я, конечно, не уверен, но мне кажется, что как раз поручни так стоять не должны, учитывая, что на других масках все в норме. Пользуясь случаем, задаю вопрос. Будет ли модель с 2-мя гофрами? У меня есть в наличии своя, но она декомпиленная, и на нее нет текстур.
