### ISSUE TITLE
81-717 МСК, кузов

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#164]
Попробовать сделать 2 гофры на кузове, что 100% потребует запара с текстурами. У меня есть моделька с 2-мя гофрами, но декомпиленная.

**Comment by Alexrig23** [comment]
https://github.com/metrostroi-repo/MetrostroiAddon/issues/146

**Comment by fixinit75** [comment]
Знаю, вынес в отдельную тему для удобства, + наработки есть в виде модели

**Comment by old702** [comment]
Повтор #146
