### ISSUE TITLE
Работа сигналки после рефакторинга кода

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#165]
Не работает !sactiv посностью.
Не работает !sopen полностью.

**Comment by TheFUlDeep** [comment]
Там какой-то трабл с глобальной функцией, которая в хуке вызывается, по-моему. Серверную часть я вроде почти не трогал

**Comment by fixinit75** [comment]
А что дает if ulx and not fromULX then return end? Она как раз всю малину и портит. Я ее закомментировал, всё сразу стало работать.

**Comment by glebqip** [comment]
Ааа, функция блокирует вызов из хука PlayerSay при наличии ulx, так как команда вынесена в ulx (чтобы у неё была возможность права устанавливать)

**Comment by fixinit75** [comment]
Только, что-то не устанавливаются права в ulx на это. Ну мб, конечно, и я тупой. но я так и не смог выдать группе на это разрешение

**Comment by TheFUlDeep** [comment]
> Только, что-то не устанавливаются права в ulx на это. Ну мб, конечно, и я тупой. но я так и не смог выдать группе на это разрешение. Да и вообще, я не вижу там эту команду

Вроде на месте все 
![image](https://user-images.githubusercontent.com/39480610/115111765-8b853c00-9f8a-11eb-94fa-8f7b1273d598.png)
![image](https://user-images.githubusercontent.com/39480610/115111770-95a73a80-9f8a-11eb-881f-312643cedc77.png)

**Comment by fixinit75** [comment]
Хмм, значит, это у меня с ulx беды, ибо она не видит этого

**Comment by fixinit75** [comment]
Более не имеет смысла держать открытым
