### ISSUE TITLE
81-717 МСК

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#169]
Я надеюсь, это только у меня так? 
![image](https://user-images.githubusercontent.com/78933401/115114513-7e6f4980-9f98-11eb-99d0-934e8fcc073b.png)

**Comment by fixinit75** [comment]
P.S, Номер маршрута выставлял не я, он сам поставился, на 00 не сбросился, как раньше.

**Comment by TheFUlDeep** [comment]
У меня такие же беды с моделями и текстурами. Юбик вообще просто весь синий)
По поводу номера маршрута не обращал внимания пока что

**Comment by CrIcKeT98** [comment]
Проблема ещё актуальна?

**Comment by fixinit75** [comment]
Ну у меня как было, так и осталось. Я завтра попробую еще раз скачать ветку, мб у меня устарела, что быть не может, т.к на прошлой неделе скачивал, буквально

**Comment by CrIcKeT98** [comment]
Отпишись от сторонних аддонов при проверке, только официальные паки.

**Comment by fixinit75** [comment]
Проверил и без сторонних и с ними, работает. Можно закрывать
