### ISSUE TITLE
Ошибка скриптов 717 СПБ в системе электрики

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#171]
**Пожалуйста, опишите найденную вами ошибку**
Ошибка скриптов, приводящая к невозможности использовать состав.

**Как воспроизвести:**
1. Спавн состава 81-717 (СПБ) С электросхемами: МПЛ/ФПЛ в состоянии "Запущен полностью"
2. Получите ошибку

**Вывод консоли**
`[string "metrostroi/systems/sys_81_717_electric.lua"]:722: attempt to perform arithmetic on a nil value`

**Скриншот вывода консоли**
![image](https://user-images.githubusercontent.com/78933401/115116601-0e19f580-9fa3-11eb-9b21-cd8b7d7b1128.png)

**Информация об игре**
 - Версия Garry's mod: обычная
 - Где происходит ошибка: сервер (свой)
 - Версия метростроя: DEV
 - Наличие пользовательских модов метростроя: есть
 - Операционная система: Windows

**Comment by fixinit75** [comment]
Конкретно: `AVO["68"]` он не может найти, он вообще в ПАМ задан?

**Comment by glebqip** [comment]
Задан
https://github.com/metrostroi-repo/MetrostroiAddon/blob/dev/lua/metrostroi/systems/sys_81_717_pam.lua#L143
https://github.com/metrostroi-repo/MetrostroiAddon/blob/dev/lua/metrostroi/systems/sys_81_717_pam.lua#L190

**Comment by fixinit75** [comment]
Смотри, не задан сам AVO. Вернее, он его не видит. А вот если, к примеру, туда вписать не чистый код, а такое: 
`
        if isKSD then
            S[68] = S["D1"]*AVO["68"]*Train.VOPD.Value
        end
        AVI.OPD = S["D1"]*Train.VOPD.Value
        --ниже строчка тоже выдавала ошибку, пока не впишешь такое же условие
        if isKSD then
            Train:WriteTrainWire(68,AVI.OPD*AVO["68"])
        end
`
То все работает отлично. Ибо там стоит условие, что:
`
        if isPUAV then
            AVI = Train.PUAV
            AVO = Train.PUAV
            ...
        else
            AVI = Train.PAM_VV
            AVO = Train.PAM
            ...
`
т.е ему надо знать, что конкретно от него ты хочешь

**Comment by glebqip** [comment]
>Смотри, не задан сам AVO

Выше строчка в электрике, используется тоже AVO

**Comment by fixinit75** [comment]
Тем не менее, он не видит, ее, мб она где-то теряется

**Comment by ImPerzz** [comment]
Баг не воспроизводится что с пользовательскими модами что с стоком.
