### ISSUE TITLE
Добавить разрядку батареи

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#172]
Ну и свечение ламп в зависимости от напряжения батареи, а не только от кол-ва работающих приборов

**Comment by glebqip** [comment]
Если кто то объяснит как рассчитывать токи разрядки в такой сложной цепи как состав из 8 вагонов, как это превратить в код и как это удобно связывать с цепями управления - без проблем

**Comment by fixinit75** [comment]
~~Можно феникса попросить~~

**Comment by alexandr-sizov** [comment]
Предлагаю закрыть issue чтобы не мазолил, один хрен реализовывать никто не будет.

**Comment by fixinit75** [comment]
Соглашусь
