### ISSUE TITLE
Привести исходники моделей к реальному скейлу в метрах

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#174]

**Comment by old702** [comment]
Вопрос: зачем, если в метрострое скейл кастомный

**Comment by cyber-dream** [comment]
Для удобства работы с моделями. Это и не удобно, выставлять в ручную в каждом софте все скейлы вручную и увеличивает ненужную вероятность ошибки. На моих тестах скейл через QC отрабатывал с приемлемой погрешностью

**Comment by CrIcKeT98** [comment]
Не требуется. В настройках сцены юниты выставляются один раз и в QC не нужно добавлять никаких параметров.
