### ISSUE TITLE
На модели 717 окна могут находится выше, чем на чертеже

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#175]

**Comment by old702** [comment]
Принципиально полностью нужна замена всех скинов (моделей и текстур) и перезапечка оных при замене высоты окон

**Comment by CrIcKeT98** [comment]
Слишком большой объем работы, поскольку потребуется переделать все скины под кузов, а также салон. Задача нетривиальна и проще создать новые модели. Считаю тратить время на это не целесообразно.
