### ISSUE TITLE
Собрать весь список масок для 717-х

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#176]
Включая варианты под "А", Будапешт и тд.

**Comment by MrSandManFM** [comment]
- [ ] 2-2 Подстекольник (с птичкой/без)
- [ ] 2-2-2 Подстекольник (с птичкой/без)
- [ ] 2-2 (с птичкой/без)
- [ ] 2-2-2 (с птичкой/без)
- [ ] 1-4-1 (с птичкой/без)
- [ ] 1-1 (с птичкой/без)
- [ ] Ретросостав 
- [ ] 1-3-1 (81-540)
- [ ] 1-4-1 (81-540)
- [ ] 1-3-1 Екб
- [ ] 1-4-1 Киев

Прошу дополнять то, что упустил
