### ISSUE TITLE
На скине лвз не хватает деталей

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#180]

**Comment by cyber-dream** [comment]
@MrSandManFM опиши подробнее

**Comment by MrSandManFM** [comment]
@cyber-dream в другом таске описано, перенести?

**Comment by cyber-dream** [comment]
Это дубль или там более глобальный таск?

**Comment by MrSandManFM** [comment]
> Это дубль или там более глобальный таск?

Там написано про это, но в ключе исправлений ЛВЗ

**Comment by cyber-dream** [comment]
Продублируй тут, пожалуйста

**Comment by MrSandManFM** [comment]
- [ ] Клепки на бампере
![image](https://user-images.githubusercontent.com/4011223/115706733-a4209800-a376-11eb-88a4-8c6f5ac45f43.png)

- [ ] Надписи на морде (номер вагона, приписка к ТЧ)

- [ ] Шов кузова с базой
![image](https://user-images.githubusercontent.com/4011223/115706835-bd294900-a376-11eb-8f27-b9c197a09172.png)
