### ISSUE TITLE
Камеры в 717

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#181]
Камеры наблюдения в салоне для машиниста

**Comment by old702** [comment]
Зачем.

**Comment by cyber-dream** [comment]
Почему бы и нет?

**Comment by MrSandManFM** [comment]
Уточнить: 
1. Есть ли в СПБ возможность машинисту смотреть камеры (вроде нет)
2. Как это сделано в МСК
3. Наличие камер в кабине МСК

Камеры в кабине СПб есть, соответсвенно их тоже надо сделать будет

**Comment by glebqip** [comment]
Ни в СПб, ни в МСК нет возможность следить машинисту за камерами. Камеры в салоне в МСК точно уходят в ситуационный центр.

**Comment by cyber-dream** [comment]
Тогда давайте закрывать, просто в детализацию салона запихнём
