### ISSUE TITLE
Модель концевиков в лвз

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#182]

**Comment by MrSandManFM** [comment]
Есть в #130

**Comment by cyber-dream** [comment]
Нет, это уже конечной таск, кому-нибудь потом выдадим. В таком контексте не дубликат

**Comment by MrSandManFM** [comment]
Тогда к той галке его как-то можно привязать? или его там удалить?

**Comment by cyber-dream** [comment]
Айдишник укажи, как с табло

**Comment by MrSandManFM** [comment]
В основном указать на этот?

**Comment by cyber-dream** [comment]
Да

**Comment by cyber-dream** [comment]
![](https://user-images.githubusercontent.com/4011223/107239334-cf633e80-6a39-11eb-83bd-1a92654a967d.png) 
Прикрепляю из родительского таска реф, по возможности сфоткать с платформы в более подробном ракурсе
