### ISSUE TITLE
Возможность рандомно генерировать разный цвет пластика в салоне

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#186]
Как вариант, через material proxy

**Comment by old702** [comment]
Варианты блендинга которые ты можешь использовать ограничиваются умножением, так что в атласе окраски будет окрашиваться полностью текстура

**Comment by cyber-dream** [comment]
Можно сделать битмапу с разноцветными квадратиками низкого разрешения, которая будет менять диффузу как нам надо. Главное, что бы хотя бы эта операция там поддерживалась)

**Comment by old702** [comment]
Ты переоцениваешь прокси, поддржка тинтмасок в гмоде отсутсвует
