### ISSUE TITLE
На потолке нет поддерживающих реек

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#190]
![image](https://user-images.githubusercontent.com/4011223/115705020-b4377800-a374-11eb-8c47-f084a9f712e2.png)

**Comment by old702** [comment]
Проверить положения вершин в модели кузова Еж

**Comment by MrSandManFM** [comment]
Стоит в целом проверить все уголки и рейки на наличие

**Comment by Alexrig23** [comment]
Когда фикс?

**Comment by CrIcKeT98** [comment]
> Когда фикс?

Могу 8 реек добавить на потолок, как в номере. Однако в том же номере количество этих реек на потолке может быть отличным от 8.

**Comment by Alexrig23** [comment]
> > Когда фикс?
> 
> Могу 8 реек добавить на потолок, как в номере. Однако в том же номере количество этих реек на потолке может быть отличным от 8.

Исправили недоработку? Если исправили то эту тему можно закрывать.

**Comment by CrIcKeT98** [comment]
Я сел исправлять эту проблему и говорю: я не буду исправлять эту ошибку. Салоны слишком кривые, несимметричные, а изменения необходимо продублировать во всех моделях. Добавление реек того не стоит.
