### ISSUE TITLE
Сделайте реальные номера у вагонов Ем-508Т и Еж3

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#195]
![image](https://user-images.githubusercontent.com/80965105/115558352-5561f800-a2bb-11eb-8840-5fa8ae2c9618.png)

в реальности к примеру должно быть 6442, 6775, 6774, 7042, 7045 и т.д

**Comment by Alexrig23** [comment]
дополняю, добавить еще реальные номера для Еж3, не все реальные есть в игре.

**Comment by glebqip** [comment]
Хорошо было бы приложить нумерацию, какой должна быть
Из викиепдии и сайта Трёхгранка: 
Еж3: 5561-5999, 9000-9049
Ем-508Т: 6398-6874, 6992-7091
