### ISSUE TITLE
Синалка, кол-во свободных б/у, считываемых одним сигналом

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#196]
Сделайте больше кол-во свободных б/у, которые может светофор увидеть. Сейчас их 10, что не дает адекватно реализовать РАБ по типу КалЛ, где есть желтые сигналы*. Да и вообще, на большие расстояния не действует РАБ из-за этого.

(*) - перегон заят: красный, свободен 1 перегон - желтый, 2 и более - зеленый
Вот пример, что оно не работает, настройки такие: 3-3-3-3-3-3-3-3-3-3-3-1-1-1-1-1-1-1-2
![image](https://user-images.githubusercontent.com/78933401/115705106-cca79280-a374-11eb-9b3b-9ca0a385c5b9.png)
Удаляем одну цифру 3 отсюда: 3-3-3-3-3-3-3-3-3-3-1-1-1-1-1-1-1-2:
![image](https://user-images.githubusercontent.com/78933401/115705215-f496f600-a374-11eb-983f-2310d9c9208f.png)
Так быть не должно, должен быть зеленый.
по-хорошему, надо повысить до 30 хотя бы
 P.S. Я понимаю, что будет лагать, но в таком случае, можно сделать так: считать как раньше 10, но если в сигнале больше, чем 10 цифр в линзах или ARScodes, то повышать ограничение: 15, 20, 30, и т.д. Ну или галкой вынести

**Comment by alexandr-sizov** [comment]
"P.S. Я понимаю, что будет лагать, но в таком случае, можно сделать так: считать как раньше 10, но если в сигнале больше, чем 10 цифр в линзах или ARScodes, то повышать ограничение: 15, 20, 30, и т.д. Ну или галкой вынести"

Первое: Лагать не должно, проблема в том что оно будет считать их вечность.

Второе: предложенный способ повышения ограничения в зависимости от вбитых lights и ARSCodes не работостопосбоен по по причине того, что счет происходит через prevSig.FreeBS += 1, в котором ограничение будет действовать прежнее. Т.е. ограничение надо снимать на всех сигналах, а не на конкретном. 

#18
#107

**Comment by glebqip** [comment]
По хорошему - переделка всей этой системы с блок участками на реальный лад
