### ISSUE TITLE
Неправильная работа информатора

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#20]
Если ты отправляешься с конечной и едешь не до конца линии, а зонно, то перед ОДЗ проигрывается "поезд следует до станции ___" Допустим отправляемся с Новоясеневской, а следуем до ВДНХ, то при отправлении с Новояса проиграется запись

**Comment by ImPerzz** [comment]
Такая штука есть только на ПУР-1 и ПНМ-6 на 760 и 77x, в метрострое вообще не понятно что по этому смысла это делать нет.
