### ISSUE TITLE
Проверить работу переключателя уставки РУТ 81-703

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#200]
Ибо не видно заметных изменений при разгоне/торможении с ним и без него. Как минимум, раньше точно оно работало

**Comment by old702** [comment]
А разве в Еже был переключатель уставки?
Кажется он только в типе Е присутствовал (для наземных участков чтобы не проскальзывать на влажных путях)

**Comment by fixinit75** [comment]
Прошу прощения, ошибся цифрой в коде вагона

**Comment by glebqip** [comment]
Проверил код, всё на месте, должно работать. Можешь распечатать RUTTarget в YAR_13A.

**Comment by fixinit75** [comment]
Да, действительно. Значит, механика работы поменялась. Ибо раньше, не было вообще эффекта раскрутки РК при торможении, пока не дойдешь до 40 км/ч, и тогда, оно очень резко начинало крутить РК.
