### ISSUE TITLE
АРС-Еж3: Сверка схем по выхинской книжке

### ISSUE THREAD

**Issue by alexandr-sizov** [metrostroi-repo/MetrostroiAddon#210]

**Comment by Alexrig23** [comment]
а у Планерной ничем не отличается?

**Comment by glebqip** [comment]
А такая книжка есть?

**Comment by alexandr-sizov** [comment]
> А такая книжка есть?
Речь про: 
![image](https://user-images.githubusercontent.com/31768135/118267281-78e81f00-b4c4-11eb-9e41-54004f87466c.png)
Почему выхинская - не помню уже

**Comment by alexandr-sizov** [comment]
Потом как нибудь.
