### ISSUE TITLE
Скриптовые ошибки при использовании ключа администратора

### ISSUE THREAD

**Issue by CrIcKeT98** [metrostroi-repo/MetrostroiAddon#219]
Ключ администратора не позволяет открыть замки на картах. При использовании ключа происходит скриптовая ошибка.
![image](https://user-images.githubusercontent.com/33666353/119878419-c2a81f00-bf32-11eb-934c-2bc324f3f842.png)
```
[Metrostroi Subway Simulator - Скрипты] lua/weapons/train_key/init.lua:27: bad argument #3 to 'Fire' (number expected, got string)
  1. Fire - [C]:-1
   2. unknown - lua/weapons/train_key/init.lua:27
```

**Comment by glebqip** [comment]
В :Fire убрать 3й аргумент
