### ISSUE TITLE
em508 скриптовой баг

### ISSUE THREAD

**Issue by pinok21** [metrostroi-repo/MetrostroiAddon#241]
Баг со скриптом головного вагона, система не работает
Также скрипты не видят сторонние скины на кузов кроме стандартных 
Просто заспавнил 508

![image](https://user-images.githubusercontent.com/60617445/123083807-1f5f0280-d429-11eb-986e-c4adeaa3edf4.png)

**Информация об игре**
 - Версия Garry's mod: обычная
 - Где происходит ошибка: свой сервер
 - Наличие пользовательских модов метростроя: есть
 - Операционная система: Windows 7

**Comment by glebqip** [comment]
Проверь наличие сторонних аддонов. По данной ошибки ничего нет по текущим скриптам на той строке, значит её создают не эти скрипты

**Comment by Doogls** [comment]
Ем508 это же пользовательский аддон, а не сам метрострой

**Comment by glebqip** [comment]
В данных скриптах он есть

**Comment by pinok21** [comment]
от него отписался, от ем 705 тоже

**Comment by glebqip** [comment]
![image](https://user-images.githubusercontent.com/6125008/123149245-bba8f980-d469-11eb-9524-8e895297f5be.png)
Ну вот тебе 61 строка, тут нету RC1. Вопросы остаются

**Comment by glebqip** [comment]
Ты же отписался от оригинальных скриптов метростроя?

**Comment by pinok21** [comment]
оу...
понял, пойду отписываться

**Comment by pinok21** [comment]
спасибо)

**Comment by pinok21** [comment]
кста, еще вопросик
Пофиксятся выбор окраски на ежовых кузовах? просто там на все скины одна окраска
