### ISSUE TITLE
Невозможно посадить срывной клапан при открытом разобщительном кране в ЗК

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#243]
При приемке 81-717 в депо наступает такой момент, когда нужно сорвать срывную скобу и посадить срывной клапан при открытом разобщительном кране и КМ во 2-м положении в другой кабине. Кран машиниста подпитывает ТМ во 2-м положении настолько быстро, что даже если открыть на составе все стоп-краны, то посадить клапан все равно вряд ли получится.

Как воспроизвести:
(Поскольку срывной клапан как на Оке на Номерном сорвать невозможно, задача усложняется)
1. Спавн 81-717 на станции.
2. Прицепить деповскую магистраль и открыть концевой кран НМ
3. Проехать запрещающий со срывом автостопа и закрыть ЭПВ(от греха подальше).
4. Попытаться посадить срывной клапан из ЗК, не закрывая разобщительный в ПК

Так же необходимо добавить возможность сорвать клапан на номерном для возможности проведения полноценной приемки.

**Comment by glebqip** [comment]
В реальности точно так же? Есть несколько авариек связанных с тем, что в хвосту дует срывной и везде необходимо его просадить, это раз. Да и вроде не так далеко всё же 8й вагон будет, чтобы там очень сильная разница давлений была. Кроме того, срывной клапан устроен по темпу разрядки же, а этот темп ну ни как не будет уменьшаться если будет постоянная подпитка из головного вагона, тут всё же необходима проверка на реальном составе или прямо точное подтверждение что оно будет просаживаться

**Comment by AlmP-RUS** [comment]
> В реальности точно так же? Есть несколько авариек связанных с тем, что в хвосту дует срывной и везде необходимо его просадить, это раз. Да и вроде не так далеко всё же 8й вагон будет, чтобы там очень сильная разница давлений была. Кроме того, срывной клапан устроен по темпу разрядки же, а этот темп ну ни как не будет уменьшаться если будет постоянная подпитка из головного вагона, тут всё же необходима проверка на реальном составе или прямо точное подтверждение что оно будет просаживаться

![image](https://user-images.githubusercontent.com/79363684/124331313-bb121080-db97-11eb-8908-ca5eae4a245c.png)
Выделил нужное (МИ ТЧ-2 Сокол 2018). Почти во всех МИ приемка одинаковая.

**Comment by glebqip** [comment]
![image](https://user-images.githubusercontent.com/6125008/124334542-16480100-dba0-11eb-9a25-f0f77a860d94.png)

**Comment by glebqip** [comment]
А, я идиот. Я понял проблему

**Comment by AlmP-RUS** [comment]
> А, я идиот. Я понял проблему. То есть если в ЗК 2 положение и в ПК 7 положение, клапан в ПК не просадится?

Абсолюти

**Comment by CrIcKeT98** [comment]
При каком количестве вагонов это тестировалось?

**Comment by AlmP-RUS** [comment]
> При каком количестве вагонов это тестировалось?

2, 4, 6, 8
