### ISSUE TITLE
На вагоне 81-508Т при нажатии на Ctrl камеры направлены не в ту сторону

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#245]
На вагоне 81-508Т (ЕМ-508Т промежуточный) при нажатии на Ctrl камеры направлены не в ту сторону

![gmod_IDrZsa5Lxp](https://user-images.githubusercontent.com/79363684/124320528-bb54e080-db84-11eb-8ce2-72da9969aed1.jpg)
![gmod_1B6DUVUSE8](https://user-images.githubusercontent.com/79363684/124320530-bc860d80-db84-11eb-9c07-96ac7cc5b05a.jpg)
![gmod_kzL3uWGglH](https://user-images.githubusercontent.com/79363684/124320533-bd1ea400-db84-11eb-91ef-50060ef674d3.jpg)

**Версия:** _dev #238_

**Comment by CrIcKeT98** [comment]
Не воспроизводится
