### ISSUE TITLE
Не правильный цвет трубок магистралей на автосцепке

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#246]
Тормозная магистраль находится сверху, а напорная снизу, когда как в метрострое наоборот.

![gmod_Lfrw2kMQ9i](https://user-images.githubusercontent.com/79363684/124321359-3b2f7a80-db86-11eb-83df-69234f9db53c.png)

В подтверждение своих слов приложу фотографию, где деповская магистраль подключена именно к нижнему пневмоклапану автосцепки.

![image](https://user-images.githubusercontent.com/79363684/124321320-2b179b00-db86-11eb-94de-11f89a67a25c.png)

**Comment by CrIcKeT98** [comment]
Цвет трубы не всегда обозначает её назначение, как например на данном фото.
![image](https://user-images.githubusercontent.com/33666353/124365677-30421c00-dc52-11eb-912e-9b86d995d01a.png)
