### ISSUE TITLE
Баг с группами фар

### ISSUE THREAD

**Issue by pinok21** [metrostroi-repo/MetrostroiAddon#247]
модели горящей группы фар не отображаются на 141 (оба варианта), на 2-2-2 glass модели свет. группы фар стандартные

**Comment by CrIcKeT98** [comment]
> модели горящей группы фар не отображаются на 141 (оба варианта), на 2-2-2 glass модели свет. группы фар стандартные
Опиши подробнее в чем проблема и приложи скриншоты

**Comment by pinok21** [comment]
Проблема в том, что (видимо) когда прописывали модели свет. фар перепутали (ну или назвали не так), потому что выходит следующее:
![gm_metro_kalinin_v10041](https://user-images.githubusercontent.com/60617445/125225397-e7d0d100-e2d7-11eb-8d64-31a3275c35a0.jpg)
(фары включены)
![gm_metro_kalinin_v10040](https://user-images.githubusercontent.com/60617445/125225418-f0c1a280-e2d7-11eb-89c0-8269def6ccf0.jpg)
модели не для подстекольника
![gm_metro_kalinin_v10039](https://user-images.githubusercontent.com/60617445/125225427-f5865680-e2d7-11eb-848a-b16d2b835974.jpg)
 ну тут и так видно
 
 причем с 2-2-2 и 2-2 (вроде) проблем нет
