### ISSUE TITLE
Скриптовые ошибки gmod_track_signal

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#249]
Бесконечный спам в консоль данной ошибки:
![image](https://user-images.githubusercontent.com/79363684/124363144-3e883c00-dc42-11eb-8b33-f625bd330806.png)

Ошибка возникает, когда поблизости есть светофор (за исключением АРС онли), и из-за нее на светофорах нету таблички с наименованием, и все линзы погашены. Иногда даже могут появиться проблемы с частотами (только 0/ОЧ)

**Информация об игре**
 - Версия Garry's mod: ![image](https://user-images.githubusercontent.com/79363684/124363180-7db68d00-dc42-11eb-8a39-dde7e5928af5.png)
 - Где происходит ошибка: локальня игра
 - Наличие пользовательских модов метростроя: есть
 - Операционная система: Windows 10
 - Версия Метростроя #238

**Comment by glebqip** [comment]
Это косвенная проблема метростроя, так как её причины:
- Неверный тип светофора, который не из метростроевских (проверки на это нету), прописанного при этом в сигналке
- Наличие пользовательского дополнения, который перезаписывает gmod_track_signal/shared.lua, либо наличие этого файла
Можно ли проверить без пользовательских дополнений?

**Comment by AlmP-RUS** [comment]
>   Можно ли проверить без пользовательских дополнений?

Ща проверим

**Comment by AlmP-RUS** [comment]
> > Можно ли проверить без пользовательских дополнений?
> 
> Ща проверим

Чисто с одним гхаб метростроем без всякого мусора данной проблемы нет. Но вся суть в том, что с версией метростроя из мастерской Стим и теми же пользовательскими аддонами такой проблемы не возникало >_<

**Comment by glebqip** [comment]
Ну ни кто не гарантирует совместимость пользовательских аддонов с этой версией, особенно если они перезаписывают файлы, которые менялись
