### ISSUE TITLE
Небольшой букет недоработок на 81-717.5М СПБ

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#252]
1. Старая реклама внутри/за новыми щитами под рекламу (актуально только для головных вагонов)
![image](https://user-images.githubusercontent.com/79363684/124364579-1bae5580-dc4b-11eb-9d17-6b7ed7e354ad.png)
![image](https://user-images.githubusercontent.com/79363684/124364589-2a950800-dc4b-11eb-94e5-b9c1b23c5db3.png)
![image](https://user-images.githubusercontent.com/79363684/124364597-3aace780-dc4b-11eb-956f-cc6fb0bc8a08.png)

2. При КРМШ 334 отсутствует уравнительный резервуар
![gmod_aWaf9QAFPt](https://user-images.githubusercontent.com/79363684/124364731-169dd600-dc4c-11eb-86f8-c9c3225cb39e.jpg)
![gmod_1MmAZoLgwJ](https://user-images.githubusercontent.com/79363684/124364732-1b628a00-dc4c-11eb-8924-a26dd481b2bc.jpg)

3. При спане состава вполне возможно получить маску с несовпадающей текстурой маски с поручнями
![gmod_5A4swdNrhp](https://user-images.githubusercontent.com/79363684/124364834-aa6fa200-dc4c-11eb-86ce-57a9662070ca.jpg)

**Comment by AlmP-RUS** [comment]
По мере нахождения багов на этом ПС буду сюда дописывать

**Comment by glebqip** [comment]
> При КРМШ 334 отсутствует уравнительный резервуар
А где он должен быть, и как выглядеть?

> При спане состава вполне возможно получить маску с несовпадающей текстурой маски с поручнями
> Старая реклама внутри/за новыми щитами под рекламу (актуально только для головных вагонов)
Данные дополнения могут быть удалены, так как не готовы

**Comment by AlmP-RUS** [comment]
> > При КРМШ 334 отсутствует уравнительный резервуар
> 
> А где он должен быть, и как выглядеть?
> 
> > При спане состава вполне возможно получить маску с несовпадающей текстурой маски с поручнями
> > Старая реклама внутри/за новыми щитами под рекламу (актуально только для головных вагонов)
> 
> Данные дополнения могут быть удалены, так как не готовы

Про резервуар актуально не только для СПБ 5М, а выглядит он вот так:
![image](https://user-images.githubusercontent.com/79363684/124366047-73ea5500-dc55-11eb-88d2-1f64556e1a40.png)
На Е шках видно лучше:
![image](https://user-images.githubusercontent.com/79363684/124366058-849acb00-dc55-11eb-868d-70eeb9b5fd22.png)
А на номерном МСК наоборот, он есть всегда, даже при 013 кране. 
Вот он на схеме:
![image](https://user-images.githubusercontent.com/79363684/124366072-a4ca8a00-dc55-11eb-818b-70e79c468338.png)

**Comment by AlmP-RUS** [comment]
Я надеюсь никому не мешаю тем, что нахожу и скидываю сюда очень много недоработок :3

**Comment by kosmik641** [comment]
> Я надеюсь никого не достаю тем, что нахожу и скидываю сюда очень много недоработок :3

Если бы доставал, думаю просто бы закрывали issues

**Comment by pinok21** [comment]
отсутствуют спрайты у фар, звуки открытия дверей старые

**Comment by CrIcKeT98** [comment]
1. Не повторяется
2. Нет возможности поставить резервуар, поскольку модель физически не влезает туда, мешаются элементы системы СОСД.
