### ISSUE TITLE
Нет анимации ВУД2 и КДЛ на ЕМ-509

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#253]
Нет анимации ВУД2 и КДЛ на ![image](https://user-images.githubusercontent.com/79363684/124365905-f70aab80-dc53-11eb-81e3-30d60e364653.png) на пульте помощника машиниста. Всегда находятся в одном и том же положении

**Comment by CrIcKeT98** [comment]
Не воспроизводится

**Comment by AlmP-RUS** [comment]
> Не воспроизводится

![image](https://user-images.githubusercontent.com/79363684/124363180-7db68d00-dc42-11eb-8a39-dde7e5928af5.png)

**Comment by CrIcKeT98** [comment]
Это одиночка?

**Comment by AlmP-RUS** [comment]
> Это одиночка?

Да
