### ISSUE TITLE
Яуза загорается cразу после отправления

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#254]
При нормальной напруге на КР (825 В) и отправлении в ход1 и выше из под всех вагонов яузы начинает и больше не перестает идти дым.
![gmod_fVaAfDJbge](https://user-images.githubusercontent.com/79363684/124366297-5918e000-dc57-11eb-8e41-efc564f992e6.jpg)
Но при этом на АСОТП никакой информации нет
![image](https://user-images.githubusercontent.com/79363684/124366303-6504a200-dc57-11eb-8cf3-0d9a604a3929.png)

**Comment by CrIcKeT98** [comment]
Не воспроизводится

**Comment by AlmP-RUS** [comment]
> Не воспроизводится

Попробуй на версии https://user-images.githubusercontent.com/79363684/124363180-7db68d00-dc42-11eb-8a39-dde7e5928af5.png

**Comment by AlmP-RUS** [comment]
Версия мс естественно с гхаба

**Comment by kosmik641** [comment]
Если это одиночка, имхо, баг считаю неважным, так как рекомендуется играть именно на выделенном сервере

**Comment by glebqip** [comment]
> Если это одиночка, имхо, баг считаю неважным, так как рекомендуется играть именно на выделенном сервере

Имхо всё же это баг, одиночка или не одиночка без разницы
