### ISSUE TITLE
Недоработки/баги ЕМ508Т

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#255]
1. Кнопка открытия правых дверей
![gmod_fvU7mG2uQC](https://user-images.githubusercontent.com/79363684/124388641-6e8c1980-dcec-11eb-840d-0204f49b24e8.jpg)

2. Перепутаны местами надписи на киловольтметре и амперметре
![gmod_pFnkGHzoBg](https://user-images.githubusercontent.com/79363684/124388693-a1361200-dcec-11eb-9a17-6ca99c2f1435.jpg)
![gmod_ZYBeGd4UzQ](https://user-images.githubusercontent.com/79363684/124388695-a3986c00-dcec-11eb-8a8e-0bffd9ca2484.jpg)

3. Отсутствует СТОП-Кран в кабине, хотя крепеж от него остался (не уверен, что он там должен быть)
![gmod_lhqW9oV7W3](https://user-images.githubusercontent.com/79363684/124388751-e4908080-dcec-11eb-9bb5-f1cbd1138f6f.jpg)

4. Есть вероятность получить такое аварийное освещение:
![image](https://user-images.githubusercontent.com/79363684/124388873-6da7b780-dced-11eb-9a0e-a07408231d14.png)

5(исправлено). Присутствуют крепления и тень от антенны (вроде это антенна), которой нет
![image](https://user-images.githubusercontent.com/79363684/124389220-e1968f80-dcee-11eb-9700-203132c1f6c5.png)

6(исправлено). Неверная коллизия в салоне около кабины [как на головном вагоне] (начертил где примерно она проходит)
![image](https://user-images.githubusercontent.com/79363684/124389441-c5dfb900-dcef-11eb-8415-9dea111ad248.png)

--По мере нахождения багов буду дополнять--

**Comment by glebqip** [comment]
> Невозможно зажечь красные фары

И не должно быть возможно, это промежуточный вагон, у которого нету некоторого оборудования.

> При использованиии ЕМ508Т как головной вагон не регестрируются проезды запрещающих

Любой промежуточный вагон не предназначен для использования как головного, у него нет УАВА, и соответственно нет системы проверки проезда запрещающих, для оптимизации. Как минимум, на нём без срыва пломб не поехать

**Comment by AlmP-RUS** [comment]
> > Невозможно зажечь красные фары
> 
> И не должно быть возможно, это промежуточный вагон, у которого нету части оборудования.
> 
> > При использованиии ЕМ508Т как головной вагон не регестрируются проезды запрещающих
> 
> Любой промежуточный вагон не предназначен для использования как головного, у него нет УАВА, и соответственно нет системы проверки проезда запрещающих, для оптимизации. Как минимум, на нём без срыва пломб не поехать

Хорошо, это удалю

**Comment by AlmP-RUS** [comment]
Добовляю еще

7. Кривые полигоны на морде и на некоторых черпаках
![gmod_oSjvetfKMF](https://user-images.githubusercontent.com/79363684/124389834-99c53780-dcf1-11eb-9c9f-bd305407deb7.jpg)
![gmod_6HvX4KLDrr](https://user-images.githubusercontent.com/79363684/124389836-9b8efb00-dcf1-11eb-8674-d74a15b22543.jpg)

**Comment by CrIcKeT98** [comment]
5 и 7 уже исправлено

**Comment by CrIcKeT98** [comment]
6 исправлено

**Comment by Hellss** [comment]
8) на сервере с турбостроем всегда в 0В стрелка напряжения двигателей

**Comment by Hellss** [comment]
4) не повторяется

**Comment by AlmP-RUS** [comment]
> 4) не повторяется

Да, это случается просто очень редко

**Comment by Hellss** [comment]
4) такое поведение нормальное

**Comment by Hellss** [comment]
В модель 508t_salon необходимо добавить основание стопкрана
