### ISSUE TITLE
Невозможно прижать ручной тормоз на 100%

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#256]
Ручной тормоз можно прижать максимум на 99% :3 
![image](https://user-images.githubusercontent.com/79363684/124390404-2113aa80-dcf4-11eb-965a-e1f2f192abb2.png)

Актуально для всех Е и Д образных

**Comment by Hellss** [comment]
Не повторяется

**Comment by AlmP-RUS** [comment]
> Не повторяется в одиночке, на сервере тоже

Проверю - напишу

**Comment by AlmP-RUS** [comment]
> > Не повторяется в одиночке, на сервере тоже
> 
> Проверю - напишу

Все еще проблема актуальна, выше 99% не хотит
![image](https://user-images.githubusercontent.com/79363684/125862714-10824501-2f5d-4136-a1a5-d25ffb6f6049.png)

**Comment by Hellss** [comment]
пофиксил округление у крайних позиций (0 и 1), так как оно шло очень долго от 0.999 до 1.0
Должно помочь
