### ISSUE TITLE
Добавить рабочие Стоп-краны и выключение дверей

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#257]
Предлагаю добавить рабочие стоп-краны и краны выключения дверей. Хотя бы на номерной.

**Comment by glebqip** [comment]
В 717 и 718 "рабочий" стоп кран уже есть (по сидушке там где он должен быть ревервсивкой)

Насчёт крана выключения дверей не уверен. Лично я его реализацию вижу только при наличии физики дверей, так как этот кран не открывает двери, а просто "разблокирует" их, позволяя свободно двигаться. Если есть идеи по реализации кроме того, что оно просто открывает двери, то хотелось бы услышать. Плюс, если его и делать, то делать на все составы (чем 717 такой особенный?)

**Comment by AlmP-RUS** [comment]
> В 717 и 718 "рабочий" стоп кран уже есть (по сидушке там где он должен быть ревервсивкой)
> 
> Насчёт крана выключения дверей не уверен. Лично я его реализацию вижу только при наличии физики дверей, так как этот кран не открывает двери, а просто "разблокирует" их, позволяя свободно двигаться. Если есть идеи по реализации кроме того, что оно просто открывает двери, то хотелось бы услышать. Плюс, если его и делать, то делать на все составы (чем 717 такой особенный?)

Чем 717 такой особенный - ну на подавляющем большинстве серверов проводятся практики именно на нём. Так исторически сложилось, что 717 самый проработанный состав в МС. Ну пока нет реализации физики дверей, то можно реализовать как в уже существующих аддонах - на дверях есть этот, как его (ButtonMap) на открытие и на закрытие вручную. 

А, еще забыл написать: предлагаю добавить возможность закрыть двери на трехгранный ключ (нужно для аварийки незакрытия/неоткрытия одного дверного проема). Еще можно реализовать незакрытие дверей при попадании под створку посторонних предметов

**Comment by CrIcKeT98** [comment]
Данная тема неоднократно поднималась и обсуждалась. В данный момент нет адекватных механизмов, позволяющих на должном уровне реализовать кран выключения дверей и зажатие предметов. Текущие реализации не устраивают разработчиков.
