### ISSUE TITLE
Баг с РРИ

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#258]
При отсутствии РРИ на карту (No cassete) если нажать первую программу, ты вылазит вот такая ошибка:
![gmod_GgJlUrBSzP](https://user-images.githubusercontent.com/79363684/124398463-7bc1fc00-dd1e-11eb-8455-cce6a6b63d5d.png)
![gmod_OZYIvnO5Fq](https://user-images.githubusercontent.com/79363684/124398464-7c5a9280-dd1e-11eb-88cb-82853ed6bd8d.png)
![gmod_An1B1bg4P0](https://user-images.githubusercontent.com/79363684/124398465-7c5a9280-dd1e-11eb-80b5-0ffe0e031b90.png)

Еж-3, ЕЖ, ЕМ509 соответственно

**Comment by kosmik641** [comment]
Там error прописан в коде, так что это нормально

**Comment by AlmP-RUS** [comment]
> Там error прописан в коде, так что это нормально

А... Зачем?

**Comment by kosmik641** [comment]
Чтобы не выполнять код, а заодно сообщить, почему информатор не работает
