### ISSUE TITLE
Статив АРС-Д

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#259]
Статив АРС стоит в обоих апаратных отсеках, хотя должен только справа. Сейчас в метрострое левый статив похож на АРС Днепр, а правый на АРС-МП
![image](https://user-images.githubusercontent.com/79363684/124511424-c1de9480-ddde-11eb-9219-2ed2f3055e69.png)

А должно все выглядеть примерно так:
![image021](https://user-images.githubusercontent.com/79363684/124511465-e0dd2680-ddde-11eb-8683-f26100cac537.jpg)

Статив АРС справа, а слева БИСы, РПДП и так далее

Я не прошу реализовывать прямо все, до мелочей, предлагаю только убрать правый статив и левый поставить на его место

**Comment by CrIcKeT98** [comment]
Учитывая количество моделей кабин 81-717, отсутствие понимания различий между ними, а также качество предоставленных исходников от @old702 я не буду этим заниматься. 
![image](https://user-images.githubusercontent.com/33666353/125926301-64a6c9e5-86f1-4e02-a931-f276da807b0d.png)
