### ISSUE TITLE
баг с окой

### ISSUE THREAD

**Issue by pinok21** [metrostroi-repo/MetrostroiAddon#260]
[metrostroiaddon-dev] addons/metrostroiaddon-dev/lua/entities/gmod_train_bogey/cl_init.lua:190: attempt to index local 'snd' (a number value)
  1. unknown - addons/metrostroiaddon-dev/lua/entities/gmod_train_bogey/cl_init.lua:190

Гитхабовская версия МС конфликтует с Окой, на нормальной версии такого нет

**Comment by pinok21** [comment]
(как добавлять labels?)

**Comment by glebqip** [comment]
Ну это вопросы же к разработчикам дополнения оки...

**Comment by pinok21** [comment]
> Ну это вопросы же к разработчикам дополнения оки...

я обновил описание

**Comment by AlmP-RUS** [comment]
Не факт, что все аддоны будут работать с новой версией. Это то же самое, что попробовать поездить на Оке на метрострой легаси

**Comment by pinok21** [comment]
![image](https://user-images.githubusercontent.com/60617445/125690462-0222a3b7-207c-400d-bb6a-e2fbf3deb927.png)
точно стороннее дополнение даёт такие ошибки?)
(вторая ошибка)

**Comment by AlmP-RUS** [comment]
![image](https://user-images.githubusercontent.com/79363684/125695024-de1b16e8-1fae-439b-8a62-dec8ad28c031.png)
Что за Сокол?

**Comment by AlmP-RUS** [comment]
Вот собственно и твое стороннее дополнение

**Comment by pinok21** [comment]
Не это
Я же написал, вторая ошибка
Та, что ниже

**Comment by CrIcKeT98** [comment]
Адаптация 81-760 под обновление будет сделано позже. Скриншот с ошибкой не связан с темой issue.

**Comment by AlmP-RUS** [comment]
> Не это
> Я же написал, вторая ошибка
> Та, что ниже

Проведи небольшой эксперимент - отпишись от **всех** аддонов, закинь в Addons эту версию метростроя, подпишись на все контент паки, зайди на какойнить b50 и данной проблемы у тебя не будет
