### ISSUE TITLE
Баг со сработкой АРС на 81-717 МСК при снижении ограничения

### ISSUE THREAD

**Issue by pinok21** [metrostroi-repo/MetrostroiAddon#261]
Некорректная сработка АРС на 81-717 (мск)
при снижении ограничения скорости срабатывает АРС даже в том случае, если фактическая скорость ниже ограниченной на 4 кмч

Это баг, или так и задумано?

**Comment by alexandr-sizov** [comment]
Это не баг. Так работают блоки БИС.

**Comment by AlmP-RUS** [comment]
Это называется подработка АРС. Такая вот особенность работы АРС-Д. Предлагаю закрыть issues, так как все работает корректно
