### ISSUE TITLE
metrostroi_wire

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#263]
Нужно добавить аргумент, с которого провод берёт питание. Например metrostroi_wire 31 32 (31 провод замкнут на 32 и соответственно наоборот). Если второго аргумента нет, или он равен 0, то тогда команда работает как раньше.

**Comment by fixinit75** [comment]
Тогда, нужно добавить еще обрыв провода, нпирмер, командой metrostroi_wire_cut <wire_number>

**Comment by alexandr-sizov** [comment]
> Тогда, нужно добавить еще обрыв провода, нпирмер, командой metrostroi_wire_cut <wire_number>

И где прикажешь обрывать? Имхо с текущей реализаций поездных проводов это будут костыли.

**Comment by AlmP-RUS** [comment]
> > Тогда, нужно добавить еще обрыв провода, нпирмер, командой metrostroi_wire_cut <wire_number>
> 
> И где прикажешь обрывать? Имхо с текущей реализаций поездных проводов это будут костыли.

Можно не обрывать, а закорачивать на землю

**Comment by CrIcKeT98** [comment]
> > > Тогда, нужно добавить еще обрыв провода, нпирмер, командой metrostroi_wire_cut <wire_number>
> > 
> > 
> > И где прикажешь обрывать? Имхо с текущей реализаций поездных проводов это будут костыли.
> 
> Можно не обрывать, а закорачивать на землю

Закоротка на землю это тоже самое, что выключение автомата.

**Comment by AlmP-RUS** [comment]
> > > > Тогда, нужно добавить еще обрыв провода, нпирмер, командой metrostroi_wire_cut <wire_number>
> > > 
> > > 
> > > И где прикажешь обрывать? Имхо с текущей реализаций поездных проводов это будут костыли.
> > 
> > Можно не обрывать, а закорачивать на землю
> 
> Закоротка на землю это тоже самое, что выключение автомата.

Не совсем. Автомат чаще всего отрубает поездной провод от вагона. Да и существует куча проводов, на которых нет автомата (Крикет, я опять тебя неправильно понял, да?))

**Comment by CrIcKeT98** [comment]
> > > > > Тогда, нужно добавить еще обрыв провода, нпирмер, командой metrostroi_wire_cut <wire_number>
> > > > 
> > > > 
> > > > И где прикажешь обрывать? Имхо с текущей реализаций поездных проводов это будут костыли.
> > > 
> > > 
> > > Можно не обрывать, а закорачивать на землю
> > 
> > 
> > Закоротка на землю это тоже самое, что выключение автомата.
> 
> Не совсем. Автомат чаще всего отрубает поездной провод от вагона. Да и существует куча проводов, на которых нет автомата (Крикет, я опять тебя неправильно понял, да?))

Нет автомата - есть плавка вставка после батареи, которая также оборвет цепь.

**Comment by AlmP-RUS** [comment]
> Нет автомата - есть плавка вставка после батареи, которая также оборвет цепь.

Я опять тебя нихрена не понял, к чему это все, автоматы, плавкие вставки, когда речь идет об обрыве провода (ну или закорачивании на 0

**Comment by AlmP-RUS** [comment]
Под обрывом я имею ввиду то, что поездной провод замыкается на землю и при попытке на него подать питание (нажать на кнопку или metrostroi_wire) оно не подастся

**Comment by AlmP-RUS** [comment]
Например: пишем metrostroi_wire_cut 8, и теперь у нас не будет пищать звонок ни от кнопки, ни от АРС

**Comment by alexandr-sizov** [comment]
> Под обрывом я имею ввиду то, что поездной провод замыкается на землю и при попытке на него подать питание (нажать на кнопку или metrostroi_wire) оно не подастся

При замыкании любого провода на нуль и подаче на него питания должно происходить какое то из событий в виде срабатывания автомата защиты / перегорании пл.вставки. Сделать это с текущей реализацией электросхем не возможно, т.к. не выполняется расчет параметров электрической цепи. Посему предлагаю считать вопрос закрытым.

**Comment by alexandr-sizov** [comment]
> Например: пишем metrostroi_wire_cut 8, и теперь у нас не будет пищать звонок ни от кнопки, ни от АРС

Ну во-первых 8 провод это не звонок.
Во-вторых - в таком функционале нужны нет - имхо. То что ты описываешь это просто де-факто "удаление" этого поездного провода, а не замыкание на землю.

**Comment by AlmP-RUS** [comment]
> > Например: пишем metrostroi_wire_cut 8, и теперь у нас не будет пищать звонок ни от кнопки, ни от АРС
> 
> Ну во-первых 8 провод это не звонок.
> Во-вторых - в таком функционале нужны нет - имхо. То что ты описываешь это просто де-факто "удаление" этого поездного провода, а не замыкание на землю. 

Извиняюсь, перепутал с 7 проводом, мой недочет

**Comment by AlmP-RUS** [comment]
Ну изначально речь шла про замыкание одного провода на другой. Я не знаю, в какой момент этот issues понесло не в ту сторону, ну да ладно

**Comment by alexandr-sizov** [comment]
Добавить команде metrostroi_wire_reset аргумент - номер провода для ресета. Без аргумента - восстанавливать все провода.
@Hellss

**Comment by AlmP-RUS** [comment]
Почему нельзя подавать питание на провода, в обозначении которых есть буквы (ф1, д12 и так далее) или мы опять упираемся в неполную реализацию электросхем?

**Comment by alexandr-sizov** [comment]
> Почему нельзя подавать питание на провода, в обозначении которых есть буквы (ф1, д4 и так далее) или мы опять упираемся в неполную реализацию электросхем? 

Потому что это вагонные провода, и живут они, в отличие от поездных проводов, внутри вагона, а конкретнее локально в функции think системы электрики.

**Comment by glebqip** [comment]
И архитектура схем поезда построена так, что их невозможно по большей части поменять.
Некоторые "провода" были пропущены для визуальной и не только оптимизации кода, да и даже на существующих это надо менять код довольно нехило, либо создавать свой "класс" для этого чтобы он сам это под капотом рулил
