### ISSUE TITLE
Зависимость давления ТЦ->ТМ 013

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#27]

**Comment by glebqip** [comment]
Сверить ещё раз

**Comment by CrIcKeT98** [comment]
А что тут сверять, если КМ-013 задает только давление в ТМ? Давление в ТЦ зависит от регулировки ВР или, иными словами, от давления в ТМ. Поэтому неважно какой КМ установлен в кабине.

**Comment by CrIcKeT98** [comment]
Введена новая пневматика от MoonHorse, неактуально.
