### ISSUE TITLE
Выбивает РП на 81-717 (МСК) при спавне

### ISSUE THREAD

**Issue by Hellss** [metrostroi-repo/MetrostroiAddon#273]
Сервер с турбостроем:
Выбивает РП на промежуточных вагонах при спавне 81-717 (МСК) в полностью запущенном состоянии после включения реверса

Одиночка:
Выбивает РП во всех вагонах на 81-717 (МСК) в полностью запущенном состоянии после включения реверса

**Comment by CrIcKeT98** [comment]
В одиночке выбивает РП после включения реверса и постановки ручки в ход или тормоз

**Comment by glebqip** [comment]
Это похоже на БВ, вероятно он не восстанавливается спавнером. Может есть разница в наличии и версии турбостроя
