### ISSUE TITLE
Схемы 81-717.0

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#288]
Так здрасте, товарищи разработчики, в более ранних issues уже заходила речь о том, что на данный момент мы имеем какую-то помесь .5 и .0, вот я хочу поднять эту тему вновь.

Мне на руки попала книжка 1990 года, в которой есть схемы силовых и вспомогательных цепей, ну и цепей управления на 717.0. Я конечно не на все 100% уверен, что в этой книжке схемы точно от .0, но различия (существенные и не очень) со схемой от .5 в ней имеются. Если нужно будет найти еще какую-либо инфу по теме, обращайтесь, буду рад вам помочь.

Надеюсь найденные мною схемки будут вам полезны :3 
~~Ждем .0 в метрострое~~

Книга: 
![image](https://user-images.githubusercontent.com/79363684/125782786-e09a8bc4-221d-4b18-ad2e-6a820aad8c1d.png)

Вот она в djvu формате:
https://dwg.ru/dnl/12110
Нужная нам информация находится в п.18 - стр 75-84 в этом файле

![image](https://user-images.githubusercontent.com/79363684/125783170-456a4f2e-bcf1-446a-ae8f-4ac8287dcf68.png)
![image](https://user-images.githubusercontent.com/79363684/125783240-b12a220b-047d-4226-96eb-db796b843035.png)
![image](https://user-images.githubusercontent.com/79363684/125783274-161bbe3a-c270-4614-95af-3a02d62485ad.png)

**Comment by Alexrig23** [comment]
Доработать Московскую версию 81-717/714 #146

**Comment by AlmP-RUS** [comment]
Крикету и Олди я скинул гугл диск с фотками книги по .0
![IMG_20210730_002626.jpg](https://user-images.githubusercontent.com/79363684/127568069-a5c0d0fa-5122-4bc1-9de2-131455a229a7.jpg)

**Comment by Alexrig23** [comment]
> Крикету и Олди я скинул гугл диск с фотками книги по .0
> ![IMG_20210730_002626.jpg](https://user-images.githubusercontent.com/79363684/127568069-a5c0d0fa-5122-4bc1-9de2-131455a229a7.jpg)

Это настоящие чистокровные схемы от базового Номерного?

**Comment by AlmP-RUS** [comment]
> 
> Это настоящие чистокровные схемы от базового Номерного?

В данной книге описаны схемы номерного на момент 81 года, тогда модификация .5 ещë не существовала

**Comment by Alexrig23** [comment]
Ну как дела со схемами?
