### ISSUE TITLE
Освещение пульта

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#289]
Вагон 81-717 головной, немного подбешивающая особенность освещения пульта, так явно быть не должно
![image](https://user-images.githubusercontent.com/79363684/125788513-2aa8a879-e558-477f-9f96-e95bb9054753.png)

**Comment by kosmik641** [comment]
Со включенными тенями всё ок
![20210715163444_1](https://user-images.githubusercontent.com/70780122/125797001-5599868e-e740-421d-a007-a5165f8633fb.jpg)

**Comment by AlmP-RUS** [comment]
> Со включенными тенями всё ок
> ![20210715163444_1](https://user-images.githubusercontent.com/70780122/125797001-5599868e-e740-421d-a007-a5165f8633fb.jpg)

А может у меня с тенями лаги и я играю без них?

**Comment by CrIcKeT98** [comment]
> Со включенными тенями всё ок
> ![20210715163444_1](https://user-images.githubusercontent.com/70780122/125797001-5599868e-e740-421d-a007-a5165f8633fb.jpg)

даже с включенными тенями эта проблема есть 
![image](https://user-images.githubusercontent.com/33666353/125851764-a431b89f-e5ea-447b-8fae-21d97e8e728a.png)
![image](https://user-images.githubusercontent.com/33666353/125851781-9087b972-a2b4-4652-9a3d-3d5524c1e551.png)

**Comment by AlmP-RUS** [comment]
> > Со включенными тенями всё ок

> 
> даже с включенными тенями эта проблема есть

Он имел ввиду галочки в Q меню, но это не решает проблему

**Comment by CrIcKeT98** [comment]
> > > Со включенными тенями всё ок
> 
> > даже с включенными тенями эта проблема есть
> 
> Он имел ввиду галочки в Q меню, но это не решает проблему

Помогает галка "Вкл. тени от остальных источников света", но галка "Режим съемки" не помогает

**Comment by AlmP-RUS** [comment]
> > > > Со включенными тенями всё ок
> > 
> > 
> > > даже с включенными тенями эта проблема есть
> > 
> > 
> > Он имел ввиду галочки в Q меню, но это не решает проблему
> 
> Помогает галка "Вкл. тени от остальных источников света", но галка "Режим съемки" не помогает

Это ладно, но без галок баг есть, значит вопрос остается открытым

**Comment by CrIcKeT98** [comment]
Нет, эти галки для того и нужны - либо катайся с бОльшим ФПС, либо получай более корректную картинку.

**Comment by AlmP-RUS** [comment]
Ну на ЕЖ3 же пофиксили (раньше тут было огромное пятно):
![image](https://user-images.githubusercontent.com/79363684/125854954-871d26e1-9b45-41ce-a8b0-217ae8cfc1e1.png)


Так в чем проблема поправить свет на номере, чтобы он не светил сквозь пульт?
