### ISSUE TITLE
Добавить задержку открытия/закрытия дверей

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#290]
Необходимо сделать так, чтобы двери открывались и закрывались примерно через 1-2, а то и 3 секунды (рандомно при спавне для каждого вагона) после нажатия на кнопку, соответственно если импульс нажатия на кнопку будет короче задержки, то двери в данном вагоне не откроются.

**Comment by CrIcKeT98** [comment]
В этом нет необходимости. Текущая реализация довольно точно отражает реальное поведение состава.
