### ISSUE TITLE
Неправильное расположение подвагонки на промежуточном вагоне

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#291]
Все подвагонное оборудование промежуточного вагона, развернуто на 180 градусов относительно кузова, то есть в метрострое, если смотреть в сторону головы (за голову вагона мы считаем ту сторону где стоят манометры, ст тормоз и др), то ГВ будут находиться справа, реостаты справа, а слева ТЦ, ОТЦ, РК и так далее: 
![image](https://user-images.githubusercontent.com/79363684/125807562-1e8e40bc-2614-49f7-96f4-ece2df2ced1d.png)
Хотя в жизни все выглядит иначе (вырезка из конспекта по электрике):
![](https://cdn.discordapp.com/attachments/800126260230488105/865241611037442098/unknown.png)

**Comment by CrIcKeT98** [comment]
Всё ясно, автор не шарит :grin: 
На самом деле салон повёрнут не в ту сторону со всеми вытекающими

**Comment by AlmP-RUS** [comment]
> Всё ясно, автор не шарит :grin: 
> На самом деле салон повёрнут не в ту сторону со всеми вытекающими

И тогда краник стояночного тоже перенести

**Comment by AlmP-RUS** [comment]
> Всё ясно, автор не шарит 😁
> На самом деле салон повёрнут не в ту сторону со всеми вытекающими

Ну мне знакомый машинист - номернист подметил, что тут не в ту сторону повернута подвагонка

**Comment by CrIcKeT98** [comment]
Кодерам, которые будут разворачивать модели:
Помните, что все изменения необходимо продублировать для всех 717 и 718.
Необходимо перенести все стрелки, автоматы, ВБ, батонмапы, стояночный тормоз и т.д. на промежутках.
Из 717-х и 718 удалить модели couch_cap_l, couch_cap_r, couch_cap_new. Теперь они вшиты в общую модель сиденьев.
Установить новое положение для откидывающегося сиденья, сейчас крышка-сиденье за пределами вагона.
Развернуть рекламу на 180 градусов и корректно установить.

**Comment by CrIcKeT98** [comment]
Необходимо только перенести ГВ и батонмап отпуска ВР
