### ISSUE TITLE
кузов Еж3 + переписать скрипт на использование звука МК для всех Е образных.

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#296]
у Еж3 образца 1973-1974 года на кузове нету между гофрами обрыва, кузов изначально у них как у Еж а начиная с образца 1975 по 1977 начали делать кузов с обрывом между гофрами, в игре присутствует лишь кузов образца 1973-1974 а 1975-1977 нет.
![638972](https://user-images.githubusercontent.com/80965105/126867812-c0887550-a420-4dd8-bf78-e8fe0f5434ce.jpg)
![810098 (1)](https://user-images.githubusercontent.com/80965105/127738663-fa04c457-b14e-43db-aa61-e04c6edf146e.jpg)
![845572](https://user-images.githubusercontent.com/80965105/126867814-121b901d-d851-488c-b33b-91f21990abed.jpg)
![1320895](https://user-images.githubusercontent.com/80965105/127738361-a63f2d2a-44ae-4d70-9986-15337e370922.jpg)

**Comment by Alexrig23** [comment]
> у Еж3 образца 1973-1974 года на кузове нету между гофрами обрыва, кузов изначально у них как у Еж а начиная с образца 1975 по 1977 начали делать кузов с обрывом между гофрами, в игре присутствует лишь кузов образца 1973-1974 а 1975-1977 нет.
> ![638972](https://user-images.githubusercontent.com/80965105/126867812-c0887550-a420-4dd8-bf78-e8fe0f5434ce.jpg)
> ![845572](https://user-images.githubusercontent.com/80965105/126867814-121b901d-d851-488c-b33b-91f21990abed.jpg)

![2021-07-24_18-43-59](https://user-images.githubusercontent.com/80965105/126873829-1b568277-a399-4df8-9827-b80a2afa76d7.png)
![2021-07-24_18-42-54](https://user-images.githubusercontent.com/80965105/126873832-30e2498f-2d2d-49b9-9a6c-b773dbf9f5e4.png)

**Comment by Alexrig23** [comment]
![2021-07-24_18-43-59](https://user-images.githubusercontent.com/80965105/126873857-66f8cee7-70b6-48a2-9e99-aff70c6521b8.png)
![2021-07-24_18-42-54](https://user-images.githubusercontent.com/80965105/126873860-3dafac32-7002-428d-b23b-f6b50e761b9d.png)

**Comment by Alexrig23** [comment]
как по мне то что я изменил в скриптах звук МК для Е образных более подходяще звучит чем от самого 717.

**Comment by Alexrig23** [comment]
Дефолтные скины для Еж3/Ем-508Т пофикшены (убрана тень от тифона около окошки машиниста и центральной торцевой двери) 
![Снимок экрана (1109)](https://user-images.githubusercontent.com/80965105/126892397-624c107b-fdfa-469b-b5d9-0967d33268cc.png)

**Comment by Hellss** [comment]
компрессоры в воркшопе в формате mp3, нужно в wav переделать их

**Comment by Alexrig23** [comment]
> компрессоры в воркшопе в формате mp3, нужно в wav переделать их

Обновил

![image](https://user-images.githubusercontent.com/80965105/127271663-979e998c-0683-4943-b784-2a19c85f28c2.png)

**Comment by CrIcKeT98** [comment]
Текстуры никто не примет, поскольку у тебя нет оригиналов, а каждое пересохранение .vtf формата ухудшает текстуру. Там цвет очень сильно начинает съезжать.

**Comment by Alexrig23** [comment]
> Текстуры никто не примет, поскольку у тебя нет оригиналов, а каждое пересохранение .vtf формата ухудшает текстуру. Там цвет очень сильно начинает съезжать.

Окей, текстуры оставляю себе.

**Comment by Alexrig23** [comment]
@glebqip @CrIcKeT98 

не отображается бортовой номер вагона с задней стороны головы Еж3 на Гитхабовской версии.

![Снимок экрана (1172)](https://user-images.githubusercontent.com/80965105/127652815-926a7599-4edc-442f-8bc0-f1fdc8cc64ba.png)
![Снимок экрана (1173)](https://user-images.githubusercontent.com/80965105/127652821-ecad3eb6-1d08-48d8-aef7-c9082d4065cd.png)

**Comment by glebqip** [comment]
@Alexrig23 Разделяй пожалуйста баги в комментариях на отдельные issue. В комментариях к другой issue это спокойно может потеряться. И не надо всех упоминать в таких случаях, ибо именно issue все просматриваются новые
