### ISSUE TITLE
Завязка ВЗ-1 от АВУ на А11

### ISSUE THREAD

**Issue by yarovoy1b** [metrostroi-repo/MetrostroiAddon#298]
В реальной жизни при выключении А11 в обоих кабинах не будет ВЗ-1 от АВУ. В метрострое положение А11 никак не влияет на работу АВУ.
![image200](https://user-images.githubusercontent.com/87938233/126903037-b2dd8208-d3be-42d8-aa65-91d4e3ecff1f.jpg)

**Comment by glebqip** [comment]
В метротсрое оно запитано через A29, как по СПБ схемам. Так что её стоит такой оставить для СПб, а для МСК запитать через А11.
