### ISSUE TITLE
Сигналка: добавить команду отключения САО на светофоре.

### ISSUE THREAD

**Issue by alexandr-sizov** [metrostroi-repo/MetrostroiAddon#310]
!sdisao <signal name>
!senao <signal name>

САО должен сменяться на ОЧ.
!senao должно только отменять примененную !sdisao, никаких САО там где не предусмотрено она включать не должна.
Логика:
Если подается САО, и применяем команду отключения - САО отключается. Если после отключения появляется разрешающая частота - отключение САО сбрасывается, если за светофоров появляется занятость - отключение САО сбрасывается (аналогично ПСу). Если выше указанные события не произошли - команда senao сбрасывает отключение.

**Comment by AlmP-RUS** [comment]
Сделать так, чтобы САО отключился при горящем ПС

**Comment by alexandr-sizov** [comment]
Давно реализовано.

**Comment by glebqip** [comment]
Может лучше !ssaodis и !ssaoen? Или !ssaooff/!ssaoon. По мне это выглядит более логично

**Comment by AlmP-RUS** [comment]
Предлагаю !saodis и !saoon

**Comment by alexandr-sizov** [comment]
> Может лучше !ssaodis и !ssaoen? Или !ssaooff/!ssaoon. По мне это выглядит более логично

Если сравнивать с именем команды ПСа, то сначала идет действие op or cl а далее на что - ps. Но в принципе ничего против не имею

**Comment by alexandr-sizov** [comment]
Предлагаю неймы команд оставить как уже сделано, учитывая что они встроены по уже существующей логике метростроя.
