### ISSUE TITLE
Дописать всю существующую реальную нумерацию для 81-717/714 в том числе .5 модификации от ЛВЗ и МВМ(ММЗ).

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#313]
81-717:
ЛВЗ: 8400—8868
ММЗ: 9050—9349  0001—0153

81-714:
ЛВЗ: 7202—8190
ММЗ: 9350—9999  0401—0496

81-717.5
ММЗ : 0154-0348, 0350
ЛВЗ: 8875-8999, 10000-10035, 10038-10094, 10097-10211, 10217-10220, 10223-10224, 10227-10246, 10249-10251, 10258-10259, 10261-10262, 10267-10279, 10311-10316, 10323-10331, 10344-10347

81-714.5
ММЗ: 0497-0699, 0703-0919
ЛВЗ: 8190-8399, 11000-11026, 11029-11155, 11158-11253, 11256-11341, 11348-11382, 11390-11399, 11404, 11407-11426, 11429-11433, 11437-11440, 11453-11474, 11483-11495, 11508-11511, 11552-11557, 11578-11596

**Comment by alexandr-sizov** [comment]
Откуда взяты номера вагонов?

**Comment by Alexrig23** [comment]
> Откуда взяты номера вагонов?

http://metro.vpeterburge.ru/wagons/717/ с этого же сайта.

**Comment by Hellss** [comment]
81-717 ММЗ часть номеров принадлежат Киеву, Новосибирску, Баку, Еревану, Самаре

**Comment by Hellss** [comment]
Пересмотрел все номера московских 717 всех модификаций по transphoto, поправил

**Comment by Alexrig23** [comment]
> Пересмотрел все номера московских 717 всех модификаций по transphoto, поправил

а всю реальную нумерацию 717.0 и .5 нет смысла писать?

**Comment by Alexrig23** [comment]
> > Пересмотрел все номера московских 717 всех модификаций по transphoto, поправил
> 
> а всю реальную нумерацию 717.0 и .5 нет смысла писать?

просто в игре есть некоторые карты с региональными метрополитенами

**Comment by Alexrig23** [comment]
> > Пересмотрел все номера московских 717 всех модификаций по transphoto, поправил
> 
> а всю реальную нумерацию 717.0 и .5 нет смысла писать?

ну и для Еж3 дописали же полную нумерацию несмотря то что он ещё в Украине в Харькове есть

**Comment by Hellss** [comment]
Ну я дописал Московскую 
Для еж3 дописали тоже вроде московские машины только

**Comment by Alexrig23** [comment]
> Ну я дописал Московскую #376
> Для еж3 дописали тоже вроде московские машины только

9000-9049 это в Харькове уже.

**Comment by Alexrig23** [comment]
@HellReach почему закрыли когда еще фикс не выложили в архив?
