### ISSUE TITLE
Не ставится 334 кран на ЛВЗ кузове 717/714 "МСК" 

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#314]
на МВМ 334 ставится а на ЛВЗ нет.
![Снимок экрана (1162)](https://user-images.githubusercontent.com/80965105/127455688-4275a7d2-8b30-4080-8bc8-57bdf3019e25.png)
![Снимок экрана (1163)](https://user-images.githubusercontent.com/80965105/127455691-fb564c6b-1116-4678-8a0d-7a05c6577006.png)
![Снимок экрана (1164)](https://user-images.githubusercontent.com/80965105/127455695-d2810c8d-ee77-499f-967b-52908c52fa8e.png)
![Снимок экрана (1165)](https://user-images.githubusercontent.com/80965105/127455697-b296e577-80f9-414b-a0b4-d879051d1887.png)

**Comment by glebqip** [comment]
Проверь, пожалуйста, на чистой игре и версии с гитхаба, а не воркшопа. Я в спавнере вижу гору лишнего и отсутствие некоторых визуальных фич текущей версии
