### ISSUE TITLE
Сигналка: починить tracksignalcontroller

### ISSUE THREAD

**Issue by alexandr-sizov** [metrostroi-repo/MetrostroiAddon#315]
Убрать просчет частот и freebs при активном флаге ControllerLogic, так как сейчас не возможно задать частоту и количество свободных БУ внешними скриптами / контроллером.

@glebqip прокомментируй. На сколько я понимаю сломано из-за централизации и АРМа.

**Comment by glebqip** [comment]
Хороший вопрос, когда это сломалось. Контроллер вообще ж был костыльным, и я не помню даже проверялся ли контроль линз и частот из хаммера. Я бы ещё добавил в контроллер задачу FreeBS, чтобы светофоры по соседству знали показание

**Comment by alexandr-sizov** [comment]
Согласен, задача FreeBS не помешает.

**Comment by toxin1pilot** [comment]
> Хороший вопрос, когда это сломалось. Контроллер вообще ж был костыльным, и я не помню даже проверялся ли контроль линз и частот из хаммера. Я бы ещё добавил в контроллер задачу FreeBS, чтобы светофоры по соседству знали показание

Раньше работало полностью, была возможность задачи всех комбинаций, теперь частично управление остаётся у светофора, да
