### ISSUE TITLE
Неправильно работает лампа бортовой сигнализации на промежуточном вагоне "Е" в составе с Ема-502/Ем-501

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#324]
https://drive.google.com/file/d/19by9Czmz0QaT8ICsF3Yy_m85KYSEPmNE/view?usp=sharing

**Comment by alexandr-sizov** [comment]
Да тут и со звуками беда, как вариант убрать рандом дверей -_-
@glebqip

**Comment by glebqip** [comment]
Скорость не та какая то по звуку, да

**Comment by Alexrig23** [comment]
Когда баг с лампами будет пофикшен?
