### ISSUE TITLE
Добавить на дефолтный скин СПБ герб и логотип Метро, номер вагона и надпись тч на морде Ема-502 + добавить возможность убирать/добавлять капельник (водосток)

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#326]
![1149429](https://user-images.githubusercontent.com/80965105/127778810-e481ac65-484b-4828-9863-61cd2a3d2199.png)
![1414436](https://user-images.githubusercontent.com/80965105/127778811-d49541b1-a816-42eb-a10d-4348ff3ad6e8.png)
![748201](https://user-images.githubusercontent.com/80965105/127778813-f17dadcd-3e9f-4f95-9a50-17cd30c807e1.png)

**Comment by alexandr-sizov** [comment]
И как ты предлагаешь номер ТЧ писать? Рельных депо? ну такой себе подход.

**Comment by Alexrig23** [comment]
> И как ты предлагаешь номер ТЧ писать? Рельных депо? ну такой себе подход.

Ну на Аквариуме, Саблезубе в игре же реализовали рандомизацию такую.

**Comment by alexandr-sizov** [comment]
#180#130

**Comment by Alexrig23** [comment]
> #180#130

как бы это Номерной а не Ема-502...

**Comment by alexandr-sizov** [comment]
> > #180#130
> 
> как бы это Номерной а не Ема-502... там конкретно не написано про Ему Питерскую.

А можно реальные баги/недоработки. И СЛИШКОМ МНОГО Питера уже?
