### ISSUE TITLE
Добавить возможность отключить выход пассажиров на конечной станции (УПО) 

### ISSUE THREAD

**Issue by korenkonder** [metrostroi-repo/MetrostroiAddon#334]
В принципе вся логика начинается в lua/entities/gmod_track_platform/init.lua со строки 354. Нужно добавить всего одну переменную, которая может быть объявлена для использования с arrlast

**Comment by ImPerzz** [comment]
Есть переменная в конфиге АСНП точно которая отключает высадку пассажиров на конечной платформе.
Убирать эту логику нет никакого смысла, если только добавить возможность настройки этой же переменной в другие системы УПО, Сармат и тд.

**Comment by korenkonder** [comment]
А я и не говорил про логику в АСНП. Файл, про который я сказал, относится к объекту платформы, на которой находятся сами пассажиры

**Comment by glebqip** [comment]
Есть ``ignorelast`` во всех информаторах
Смысла добавлять в платформу не вижу, ибо даже логически такая штука должна быть на стороне поезда.
Единственное что может понадобится, это отдельная логика для конечных с оборотом, где все пассажиры из вагона выходят и входят с платформы (и может быть с соседнего пути берутся), но это не относится к этому issue

**Comment by korenkonder** [comment]
Проверил сейчас код. Да, `ignorelast` есть, но не в УПО (хотя вроде бы кому он нужен, но возможность оборота на такой станции с составом ЛВЗ без высадки всех пассажиров была бы хороша)
