### ISSUE TITLE
Ема502: Последний КВР.

### ISSUE THREAD

**Issue by AlmP-RUS** [metrostroi-repo/MetrostroiAddon#336]
Я приехал в Питер, и заметил на некоторых составах КВЛ панель автоматиков за местом помощника машиниста. (Приложу несколько фоток из инета) 
![704917.jpg](https://user-images.githubusercontent.com/79363684/128066863-57a4184b-1f23-4adf-8c81-7fca720d0faa.jpg)![578631.jpg](https://user-images.githubusercontent.com/79363684/128066964-59f7e5bf-ee28-4c3a-956e-7b565773a0ff.jpg)![112651.jpg](https://user-images.githubusercontent.com/79363684/128066973-3ac7c963-4028-4c72-ae12-ec49bd852c90.jpg)

Это единичные случаи или это результат модернизации? Если это результат модернизации, то почему этого нету в метрострое?

**Comment by glebqip** [comment]
Это последний КВР, и требует моделей кабины, салона и версии промежуточной Ем без кабины

**Comment by AlmP-RUS** [comment]
> Это последний КВР, и требует моделей кабины, салона и версии промежуточной Ем без кабины

Мне попался состав с такими головами и с промежуточными кабинами

**Comment by AlmP-RUS** [comment]
И ещё вопрос, у вас есть инфа по изменениям в этом КВР и будете ли вы этим заниматься?

**Comment by CrIcKeT98** [comment]
Я не буду этим заниматься

**Comment by AlmP-RUS** [comment]
Сегодня мне попался состав, в котором только часть промежуточных вагонов не имеют кабину. То есть в новые кврные составы по схеме совместимы со старыми, потому что вот сейчас я нахожусь в составе, который состоит и из старых и из новых вагонов

**Comment by alexandr-sizov** [comment]
То что совместимы это конечно хорошо (и логично). Но схем их нет. За схемы даже я наверное взялся бы. Моделей нет - вот это проблема. Крикет моделить не будет. Будут модели - будет вагон.

**Comment by alexandr-sizov** [comment]
#155 duplicate
