### ISSUE TITLE
Освещение кабины вкл, свечения нет

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#35]
![unknown](https://user-images.githubusercontent.com/3523514/103455377-8fec5880-4cfd-11eb-9b83-f239112ed322.png)

**Comment by kosmik641** [comment]
Работает же всё
![20210709055414_1](https://user-images.githubusercontent.com/70780122/125016500-1fdad880-e07a-11eb-92f2-4648decdf3ee.jpg)

**Comment by CrIcKeT98** [comment]
Не повторяется, всё исправно.
