### ISSUE TITLE
Неверная позиция фар на 81-717 с масками 2-2-2 Glass

### ISSUE THREAD

**Issue by AlexeyQ13** [metrostroi-repo/MetrostroiAddon#352]
**Пожалуйста, опишите найденную вами ошибку**
Неверная позиция фар на масках 2-2-2 Glass.

**Как воспроизвести:**
Необходимо заспавнить состав 81-717 (МСК кастом) с масками: 2-2-2 Glass и 2-2-2 Glass (M)

**Скриншоты**

![image](https://user-images.githubusercontent.com/42507256/128875795-b42d3bae-57c2-42cf-8905-77ebf6df0801.png)

![gmod_1oilYEGRf7](https://user-images.githubusercontent.com/42507256/128875654-f6febbbe-8b3a-453d-a52f-387afab205a6.jpg)

**Информация об игре**
 - Версия Garry's mod: x86-64
 - Где происходит ошибка: локальный выделенный сервер
 - Наличие пользовательских модов метростроя: есть
 - Операционная система: Windows 10

**Comment by CrIcKeT98** [comment]
Необходимо поправить код для маскок mask_222_glass и mask_222_glass_wp, заменив им фары на headlights_222_glass_group1 и headlights_222_glass_group2
