### ISSUE TITLE
Не совсем верная работа КШ-1, КШ-2

### ISSUE THREAD

**Issue by yarovoy1b** [metrostroi-repo/MetrostroiAddon#357]
При выходе в режим Ход-3, когда включаются КШ-1, КШ-2, и последующей кратковременной (до разбора схемы) постановке ГРКВ в 0 и затем в Ход-1, оба КШ должны отпасть, т.к. у них нет задержки на отключение. В Метрострое они остаются включенными до полного разбора схемы.

**Comment by yarovoy1b** [comment]
Проверялось на составе 81-717

**Comment by alexandr-sizov** [comment]
Сейчас они встают на самоблокировку получая питание с 10 провода. Судя по всему сделано по книге 1993 года, Руководство по эксплуатации 81-717. Но видмио просто перепутали вагонный провод 10А который получает питание через В30 и ВБ с поездными 10.
![image](https://user-images.githubusercontent.com/31768135/129661014-040c116c-6dbb-4e9e-98ef-3234c7614701.png)
По УПЦшным схемам действительно запитка самоблокировка с 20 провода через контакт ЛК5

**Comment by alexandr-sizov** [comment]
Делаю вариант с запиткой через А30 и ВБ по согласованию с Глебом (схема 81-717.5). Но работа КШ в нормальном режиме не изменится, т.е. в выбеге отключение только после разбора схемы (контактом ППУ) останется.

**Comment by yarovoy1b** [comment]
Эх, жаль. Можно было бы делать пушку-гонку.)

**Comment by alexandr-sizov** [comment]
> Эх, жаль. Можно было бы делать пушку-гонку.)

поясни?

**Comment by yarovoy1b** [comment]
> > Эх, жаль. Можно было бы делать пушку-гонку.)
> 
> поясни?

Ну смотри: ты выходишь на режим Ход-3, а потом его через 0-Х1 отменяешь -- тяговое усилие ослабевает. В силу внешнего воздействия профиля пути скорость падает, а потом ты опять даешь Ход-3 и вся тяга возвращается. Получается разгон, как на нитро.) Ну если РП не хлопнет, конечно.)

**Comment by old702** [comment]
Кстати поддерживаю последнее, оно вроде проскакивает в реале иногда
