### ISSUE TITLE
Особенность запитки дверных кнопок

### ISSUE THREAD

**Issue by yarovoy1b** [metrostroi-repo/MetrostroiAddon#358]
Если в головной кабине включен реверс и заблокирован ВЗД и в хвостовой кабине заблокировать ВЗД, то поступит питание на кнопки отрытия дверей в хвостовом вагоне. Это особенно хорошо видно на упрощённой схеме:

![image373](https://user-images.githubusercontent.com/87938233/129871306-6803435f-15a0-4bb1-af64-4e442365beb9.jpg)

В метрострое вышеописанная особенность не реализована.

**Comment by CrIcKeT98** [comment]
https://youtu.be/kIG_vhPBQYs
Саня ©
