### ISSUE TITLE
Переводы

### ISSUE THREAD

**Issue by alexandr-sizov** [metrostroi-repo/MetrostroiAddon#365]
![image](https://user-images.githubusercontent.com/31768135/131192192-ce85f379-aa2b-45af-9899-1d260e3cb1f1.png)

**Comment by Hellss** [comment]
не повторяется
![image](https://user-images.githubusercontent.com/16958912/131913600-366ec225-3c04-48b3-86da-c49811e0b9af.png)
![image](https://user-images.githubusercontent.com/16958912/131913625-be1099df-cfc4-44a2-a450-285af2444eed.png)

**Comment by alexandr-sizov** [comment]
Кхм, возможно у меня поехало чо-то
Вечером проверю еще раз
