### ISSUE TITLE
УДКСТ 81-717 МВМ

### ISSUE THREAD

**Issue by CrIcKeT98** [metrostroi-repo/MetrostroiAddon#377]
Предлагаю добавить Устройство Дополнительного Контроля Стояночного Тормоза УДКСТ для 81-717 МВМ.
Звук тонального устройства, тумблер и светодиод в игре уже присутствуют. Необходимо добавить модель плашки с текстом ВКСТ и ИСТ.
Логика работы:
При наличии питания на 1-м поездном проводе начинает заряжаться конденсатор C1, благодаря чему достигается выдержка по времени на включение около 5с. Если на 64-м поездном проводе имеется питание, то устройство включает тональное устройство и миганиет светодиодом. Светодиод мигает с частотой 3Гц. При снятии питания с 1-го провода устройство отключается практически моментально.
Тумблер ВКСТ отключает устройство.

![image](https://user-images.githubusercontent.com/33666353/132258679-e4368800-f95d-4944-8998-b26f21320d21.png)

Имеется несколько вариантов установки светодиода ИСТ и тумблера ВКСТ: над кнопкой КРМК (КАХ) и под ней на 7-м блоке.
Проще сделать вариант над кнопкой, т.к. для варианта "под" необходимо двигать другие элементы

![image](https://user-images.githubusercontent.com/33666353/132359250-e2b3a9bd-b4f0-4c44-b961-78847572d34a.png)

![image](https://user-images.githubusercontent.com/33666353/132260935-7c92322a-5b41-44de-b8f3-7785c6380625.png)

**Comment by BlueSnooty** [comment]
А ты разобрался, как подается питание на схему с КРУ? Я тогда так и не понял
