### ISSUE TITLE
Питание АСНП

### ISSUE THREAD

**Issue by ImPerzz** [metrostroi-repo/MetrostroiAddon#379]
Запитать АСНП согласно схеме и отвязать от автомата А61(АС1).
Сейчас питание АСНП сделано через тумблер ВБ и А61(АС1).

![image](https://user-images.githubusercontent.com/24627327/135760945-6f937ea2-b925-4bf2-a59e-55e5dff9c509.png)

**Comment by alexandr-sizov** [comment]
так же проверить питание иглы
