### ISSUE TITLE
Отсутствуют отверстия в резинке (низкая детализация резинки) между дверьми у Еж3/Ем-508Т и остальных Е-образных, возможно отсутствует сама модель резинки.

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#380]
![Снимок экрана (1428)](https://user-images.githubusercontent.com/80965105/138144071-a352e83d-4aca-49ad-bd44-a041d599ad0d.png)
![Снимок экрана (1427)](https://user-images.githubusercontent.com/80965105/138144076-7fae8907-d539-41ef-aa83-29db69e24484.png)
![Снимок экрана (1426)](https://user-images.githubusercontent.com/80965105/138144077-bb4d9ce7-34ab-4c54-b95d-6b33689d1567.png)
![Снимок экрана (1429)](https://user-images.githubusercontent.com/80965105/138144079-c4dee9e4-929f-4cdf-95b5-280032d14a48.png)

Прошу не быть равнодушным и исправить данную недоработку. Как в жизни так и в 2017 версии Метростроя была резинка с отверстиями чётко видна (хорошо проработанной) а в игре после обновления появилась данная недоработка и отверстия с внутренней стороны вагона тоже есть. Странно что после обновления кажутся что некоторые вагоны в плане детализации и проработки ухудшились чем что было в 2017.

**Comment by Alexrig23** [comment]
![image](https://user-images.githubusercontent.com/80965105/140637436-7da78ff3-c003-4517-96a7-76416de70f1a.png)

**Comment by alexandr-sizov** [comment]
Как не ловко, но как похуй (с) Oldy

**Comment by Alexrig23** [comment]
> Как не ловко, но как похуй (с) Oldy

Ну а вообще как эта моделька резинки называется?

**Comment by Alexrig23** [comment]
> Как не ловко, но как похуй (с) Oldy

и зачем надо было удалять её?

**Comment by Alexrig23** [comment]
> Как не ловко, но как похуй (с) Oldy

я бы с удовольствием вернул модельку резинки но я название его в файлах метростроя не знаю

**Comment by Alexrig23** [comment]
![Снимок экрана (1582)](https://user-images.githubusercontent.com/80965105/143444205-56d59f88-116a-4f48-8c01-be00f31ceedb.png)
Вот я посмотрел модели дверей из 2018 версии, резинка там есть а в игре почему не видно её?
![Снимок экрана (1580)](https://user-images.githubusercontent.com/80965105/143444198-6ec391f0-7617-4277-ac54-7cb189696ced.png)
![Снимок экрана (1581)](https://user-images.githubusercontent.com/80965105/143444201-f42d2b23-04ab-449d-af40-7be4fb9ff4e2.png)

![Снимок экрана (1583)](https://user-images.githubusercontent.com/80965105/143444178-162661a4-aece-4050-bdf1-e796c98742d2.png)
