### ISSUE TITLE
Potential typo in autorun/metrostroi.lua

### ISSUE THREAD

**Issue by LillyWho** [metrostroi-repo/MetrostroiAddon#381]
Line permalink: https://github.com/metrostroi-repo/MetrostroiAddon/blob/41f81c0ad5e716f066ad907109f1cec5408dbd48/lua/autorun/metrostroi.lua#L197

"stbl.have_interchange" is spelled "stbl.have_inrerchange

**Comment by CrIcKeT98** [comment]
Not bug.
