### ISSUE TITLE
Черный кусок текстуры

### ISSUE THREAD

**Issue by kosmik641** [metrostroi-repo/MetrostroiAddon#383]
На боковинах сидушек в текстуре Wood interior 1 нету текстуры дерева, просто чернота
![20211101182417_1](https://user-images.githubusercontent.com/70780122/139696716-f94dcaca-a850-4715-a559-e8fe8f3daaa5.jpg)

**Comment by old702** [comment]
Это неиспользуемая клиентская текстура - удалить
