### ISSUE TITLE
кривой UI под линуксом

### ISSUE THREAD

**Issue by hjri** [metrostroi-repo/MetrostroiAddon#397]
см также: https://github.com/metrostroi-repo/metrostroi_beta/issues/70

**Пожалуйста, опишите найденную вами ошибку**
Под линуксом управление контролами поезда возможно только если metrostroi_fov = fov_desired и если зажать кнопку C, иначе то что под перекрестем не будет совпадать с тем чем управляешь

**Как воспроизвести:**
Пошагово, как нам повторить эту ошибку у себя.
Пример:
1. \>Install Gentoo
2. Заспавнить любой состав с контролами (т.е. не татру)
3. Попытаться навести перекрестие на что угодно
4. Получаете неправильный контрол

**Вывод консоли**
(нет ошибок)

**Скриншот вывода консоли**
![image](https://user-images.githubusercontent.com/3514245/144510861-07d96ca9-20a3-4663-a896-a83af8af1113.png)

**Информация об игре**
 - Версия Garry's mod: x64/chromium
 - Где происходит ошибка: клиент (линукс)
 - Наличие пользовательских модов метростроя: есть
 - Операционная система: Linux Native

**Comment by hjri** [comment]
отчасти баг гмода: https://github.com/Facepunch/garrysmod-issues/issues/4964

**Comment by CrIcKeT98** [comment]
Не относится к моду, баг Гмода.
