### ISSUE TITLE
Не открывается спавн меню на своем сервере в Garrry s Mod metrostroi

### ISSUE THREAD

**Issue by odintsovvsevolod** [metrostroi-repo/MetrostroiAddon#398]
**Discribe an error**
 - Description
 - Screenshot (if applyable)
 - Train
 - Помогите решить проблему! Не открывается спавн меню на q и F1 на своем сервере! Обновление сервера делал через стим цмд не помогло... Игру переустанавливал. На остальных серверах и в одиночке все нормально было и без переустановки игры. От самой панели при заходе на сервер без нажимания кнопок самого меню высвечивается маленький кусоче с инструментом и опшинсом со стрелками как на фото и в консоли сервера и консоли игры вот такие ошибки как на фото. Последние аддоны которые добавил недавно удалял не помогло. Опишите решение проблемы подробно, пожалуйста.

**How it should be:**
 - Description 
 - Photo
![TRLP-B2TZLI](https://user-images.githubusercontent.com/95537666/144715141-7d4cbee5-99f1-4782-b8e6-01b6e46e49f0.jpg)
![REgIdL6sz30](https://user-images.githubusercontent.com/95537666/144715143-e7234396-13b7-4862-9419-cdb30c8555d6.jpg)
![hqqX1SdNwXc](https://user-images.githubusercontent.com/95537666/144715145-7973b9d3-9605-46fb-b8ac-2071b582a61a.jpg)
![aYJ9h0XCnDk](https://user-images.githubusercontent.com/95537666/144715149-df1e8a68-fadf-4d90-8986-61b9d8aff84b.jpg)
![461f28-pk9M](https://user-images.githubusercontent.com/95537666/144715152-0bd0b139-cba8-42a6-bd21-5fbccfbdf936.jpg)

**Comment by NekitPas** [comment]
решил проблему? подскажешь решение?
