### ISSUE TITLE
Не открывается спавн меню на своем сервере в Garrry s Mod metrostroi

### ISSUE THREAD

**Issue by odintsovvsevolod** [metrostroi-repo/MetrostroiAddon#399]
Помогите решить проблему! Не открывается спавн меню на q и F1 на своем сервере! Обновление сервера делал через стим цмд не помогло... Игру переустанавливал. На остальных серверах и в одиночке все нормально было и без переустановки игры. От самой панели при заходе на сервер без нажимания кнопок самого меню высвечивается маленький кусоче с инструментом и опшинсом со стрелками как на фото и в консоли сервера и консоли игры вот такие ошибки как на фото. Последние аддоны которые добавил недавно удалял не помогло.
Опишите пожалуйста как устранить подробно
**Скриншот вывода консоли**
В дополнению к коду приложите и скриншот консоли.
![TRLP-B2TZLI](https://user-images.githubusercontent.com/95537666/144715753-22d2d745-b030-454d-a578-f31c2b070433.jpg)
![REgIdL6sz30](https://user-images.githubusercontent.com/95537666/144715759-54e086cd-0eeb-4ddd-bb2d-62c038eb3b06.jpg)
![hqqX1SdNwXc](https://user-images.githubusercontent.com/95537666/144715765-e37861cc-7da9-4e5f-9770-fdaeeebe10d1.jpg)
![aYJ9h0XCnDk](https://user-images.githubusercontent.com/95537666/144715766-9c8b9bab-0c9e-4ef3-932a-40bf63613574.jpg)
![461f28-pk9M](https://user-images.githubusercontent.com/95537666/144715769-6cd0f9a7-6e0f-4c66-b2f0-a10ae378d645.jpg)

**Информация об игре**
 - Версия Garry's mod: обычная/x64/dev-branch/chromium
 - Где происходит ошибка: сервер (напишите, какой)/локальный сервер
 - Операционная система: Windows

**Comment by hjri** [comment]
это связано с MetrostroiAdvanced https://steamcommunity.com/sharedfiles/filedetails/?id=1838480881 его нужно переустановить на сервере (и возможно на клиенте тоже)

**Comment by odintsovvsevolod** [comment]
Спасибо
