### ISSUE TITLE
Реализация кранов ТМ, ТЦ, ОТЦ

### ISSUE THREAD

**Issue by yarovoy1b** [metrostroi-repo/MetrostroiAddon#406]
Было бы неплохо по-возможности сделать недостающие пневматические краны в целях увеличения реализма и возможности отыгрывать случаи.

**Comment by CrIcKeT98** [comment]
Не будет реализовано, поскольку необходимо разделять салон на дополнительные подмодели, к тому же если делать, то делать для всех составов.
