### ISSUE TITLE
Предлагаю добавить ещё несколько необычных звуков БПСН для 81-717 МСК

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#419]
https://www.youtube.com/watch?v=Fk3uHzmO05c&t=2s
https://www.youtube.com/watch?v=AeitYsd5XpU
https://www.youtube.com/watch?v=zcvb7vjXymk

**Comment by alexandr-sizov** [comment]
Какой это нафиг БАГ? ё моё!

**Comment by alexandr-sizov** [comment]
Почитай что такое баг, прежде чем ставить этот тег
https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%BD%D0%B0%D1%8F_%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0

**Comment by alexandr-sizov** [comment]
13 звуков уже есть, куда больше?

**Comment by Alexrig23** [comment]
> Какой это нафиг БАГ? ё моё!

А я могу выбирать только репорт бага модели либо скриптов..

**Comment by Alexrig23** [comment]
> 13 звуков уже есть, куда больше?

Лишним для разнообразия не будет)

**Comment by kosmik641** [comment]
Не входило в roadmap обновления
