### ISSUE TITLE
Лишние спрайты 81-717 СПБ ПБЛ, отображение ЛУДС

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#421]
На ПБЛ версии откуда-то лишние спрайты на пульте
![image](https://user-images.githubusercontent.com/78933401/147876680-2b86d044-2850-4e1f-81f4-22bf25b719b0.png)
![image](https://user-images.githubusercontent.com/78933401/147876718-8b7b6c28-44a1-474a-9d1b-095145e02120.png)

И с блоком ЛУДС явно какие-то беды, внутри него есть еще один, и работает только он.
![image](https://user-images.githubusercontent.com/78933401/147876843-22742f7f-efd2-414f-ba86-d0326ef5cd55.png)
![image](https://user-images.githubusercontent.com/78933401/147876865-7eb25186-af46-461c-9064-8427c9c321d3.png)

**Comment by CrIcKeT98** [comment]
1. Не повторяется
2. Уже исправлено
