### ISSUE TITLE
81-720, звук работы САУ

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#422]
Находится в салоне возле 2-го окна слева по ходу движения. Проверьте, мб только у меня так. По желанию, могу предоставить видео материал.

**Comment by Hellss** [comment]
Звук витязя = звонку
по скриптам он в кабине (по x 409)
Не повторяется

**Comment by fixinit75** [comment]
> Звук витязя = звонку по скриптам он в кабине (по x 409) Не повторяется

Не совсем. Это звук сигнализации витязя. Есть еще статичный звук работы ЭЛТ, который раньше (в 2017-м метрострое) был в кабине, но уже с обновы 18-го года он переместился в салон. Повторюсь, что могу записать видео, демонстрируя этот звук.

**Comment by fixinit75** [comment]
Вот, пожалуйста, тот самый звук в скрипте.
![image](https://user-images.githubusercontent.com/78933401/148538691-4d9397aa-59ba-4080-8315-0349a4f588b0.png)

**Comment by Hellss** [comment]
точно ли это звук САУ?

**Comment by Hellss** [comment]
этот звук по скриптам появляется когда напряжение на батарее есть

**Comment by fixinit75** [comment]
Ну, вообще, звучит, как ЭЛТ, но я не исключаю, что это может быть что-то еще. Но оно, как минимум, раньше было не в салоне. По-хорошему, надо уточнить.

**Comment by fixinit75** [comment]
Не имею точных данных, откуда исходит звук. Issue неактуален.
