### ISSUE TITLE
На двигателях Ежа напряжение(?) 12 вольт?

### ISSUE THREAD

**Issue by ImPerzz** [metrostroi-repo/MetrostroiAddon#436]
![image](https://user-images.githubusercontent.com/24627327/148640607-af1b8803-4ce8-4f50-b5dd-129e9b97e428.png)

**Comment by Hellss** [comment]
не повторяется

**Comment by ImPerzz** [comment]
> не повторяется

Пробуй в движении на разных участках пути

**Comment by alexandr-sizov** [comment]
В эту же тему, 717 (мб еще какие составы), при постановке в тормоз при стоянке ток -2А
upd: на Еже так же

**Comment by Hellss** [comment]
-2А да бывает такое, но на движках 12В не было

**Comment by Hellss** [comment]
> В эту же тему, 717 (мб еще какие составы), при постановке в тормоз при стоянке ток -2А upd: на Еже так же

это округление до 2
надо посмотреть как оно так округляет

**Comment by Hellss** [comment]
Это связано с округлением PackedRatio

**Comment by Hellss** [comment]
SetPackedRatio = значение*500
GetPackedRatio = полученное/500

**Comment by Hellss** [comment]
короче это связано с минимальным магнитным потоком двигателя он >= 0.01, напряжение = поток * скорость вращения, так напряжение будет прямо пропорционально скорости в выбеге

**Comment by Hellss** [comment]
glebqip:
Ну напряжение на самом двигателе будет, в цепи силовой нет
