### ISSUE TITLE
Баг модели ЛУДС на 81-717 СПБ

### ISSUE THREAD

**Issue by ImPerzz** [metrostroi-repo/MetrostroiAddon#438]
Проблема с моделью из за чего все огни и сегменты проваливаются за модель(такое ощущение что модель двух слойная без стекла)

![image](https://user-images.githubusercontent.com/24627327/148649405-2e8d848d-3cff-4898-93ac-0042231044af.png)
![image](https://user-images.githubusercontent.com/24627327/148649417-fc05af15-2c13-46c4-948a-7efb912b8895.png)

**Comment by fixinit75** [comment]
#421
