### ISSUE TITLE
Пассажиры пропадают при любом скейле

### ISSUE THREAD

**Issue by Hellss** [metrostroi-repo/MetrostroiAddon#446]
Выставляем metrostroi_passengers_scale > 500 (лучше 600)
Смотрим на появление пассажиров на станции
И спустя некоторое время они все пропадают (когда достигли предела) и начинают спавниться заново

**Comment by Hellss** [comment]
При малом скейле оказалось тоже пропадают (надо долго подождать)

**Comment by kosmik641** [comment]
Проверь с ``metrostroi_time_old 1`` на малом скейле

**Comment by Hellss** [comment]
тоже пропадают (если скейл >= 1024), если долго ждать
