### ISSUE TITLE
Добавить ещё одну неисправность для РКСУшных вагонов "Cамоход одного (головного) вагона"

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#452]
В игре на данный момент из самохода реализовано только "Самоход всего поезда"

**Comment by BlueSnooty** [comment]
Самое смешное, что технически такая возможность в метрострой заложена, но не предусмотрено способа прямого управления неисправностями пользователем, в данном случае, залипание одновременно 4 линейных контакторов одного вагона. Это может произойти случайно, при использовании команды metrostroi_fail, но так как она рандомна, то шанс получить именно самоход одного вагона примерно такой же, как шанс, что рандомный генератор букв и цифр вдруг сгенерит целый абзац осмысленного связанного текста :)
Получается, что данный запрос сводится не конкретно к самоходу вагона, а к тому, чтобы расширить консольную команду metrostroi_fail, так чтобы она воспринимала параметры, что именно и как ломать

**Comment by Alexrig23** [comment]
> Самое смешное, что технически такая возможность в метрострой заложена, но не предусмотрено способа прямого управления неисправностями пользователем, в данном случае, залипание одновременно 4 линейных контакторов одного вагона. Это может произойти случайно, при использовании команды metrostroi_fail, но так как она рандомна, то шанс получить именно самоход одного вагона примерно такой же, как шанс, что рандомный генератор букв и цифр вдруг сгенерит целый абзац осмысленного связанного текста :) Получается, что данный запрос сводится не конкретно к самоходу вагона, а к тому, чтобы расширить консольную команду metrostroi_fail, так чтобы она воспринимала параметры, что именно и как ломать

я имел в виду в команду metrostroi_wire

**Comment by BlueSnooty** [comment]
С помощью metrostroi_wire невозможно сделать самоход одного вагона. Разве что предварительно разъединить ЭКК
