### ISSUE TITLE
Не работает turbostroi_clear_cache

### ISSUE THREAD

**Issue by SmileDoge** [metrostroi-repo/MetrostroiAddon#454]
когда пытаешься ввести turbostroi_clear_cache выдает что команда не существует

версия srcds - 32 бита
версия турбостроя - самая новая с гитхаба, тоже 32 бита

на мой взгляд можно просто сделать функцию для Turbostroi.ClearCache(), ибо turbostroi_clear_cache регистрируется через C++, возможно после обновы гмода все сломалось

![image](https://user-images.githubusercontent.com/45243209/153455183-a8357208-494c-48cf-b233-14a103df483a.png)
![image](https://user-images.githubusercontent.com/45243209/153455257-f7396937-2aad-41ae-a98f-8d56850dcbfa.png)

**Comment by fixinit75** [comment]
Не воспроизводится.

**Comment by SmileDoge** [comment]
а какая версия srcds?
просто у меня такая
![image](https://user-images.githubusercontent.com/45243209/153525904-f01b4e42-f334-485b-9885-cd224ed20997.png)

**Comment by SmileDoge** [comment]
вот старый srcds с новым метростроем
![image](https://user-images.githubusercontent.com/45243209/153650884-d8c44cd8-39f0-4bf7-8026-a75ebfc7c2a5.png)

**Comment by SmileDoge** [comment]
только что обновил другой сервер, заработал
![image](https://user-images.githubusercontent.com/45243209/153651860-62682d53-ca88-49fc-aa30-9adef1ca4560.png)
