### ISSUE TITLE
Make disabling occupation check have priority over pass occupation check when the repeater route is active

### ISSUE THREAD

**Issue by LennDoMations** [metrostroi-repo/MetrostroiAddon#477]
**Describe the error**
Make occupation check disabling (route number over using acrtive repeater route) have priority over pass occupation check.

**How to get:**
1. make a signal with repeater route and routenumber
2. spawn a train infront of the signal
3. occupation check should be disabled until you activate (pass occupation signal) checkbox.

**Console output**
None

**Console output screenshot**
None

**Game information**
 All stock addon. doesnt matter much.

**Comment by LennDoMations** [comment]
+ passing the occupation signal to the next signal doesnt transfer to the next set signal but rather to the next signal on the track!

**Comment by LennDoMations** [comment]
@Pollitto

**Comment by alexandr-sizov** [comment]
Its normal repeater logic. And what do you means by routenumber? Checkbox in route config section?

**Comment by LennDoMations** [comment]
> Its normal repeater logic. And what do you means by routenumber? Checkbox in route config section?

What is normal repeater logic? that it doesnt disable occupation check when pass occupation signal is activated?

**Comment by alexandr-sizov** [comment]
Will i get an answer to the question as to what do you mean by routenumber?

No answer = close issue.

I never have a problems with repeaters and check occupation.

**Comment by alexandr-sizov** [comment]
And you can make video with problem.

**Comment by LennDoMations** [comment]
When you have a routnumber in your signal and an active repeater route it should disable occupation check all the time

**Comment by alexandr-sizov** [comment]
> When you have a routnumber in your signal and an active repeater route it should disable occupation check all the time

why would you use a route pointer and a repeater route at the same time?

**Comment by alexandr-sizov** [comment]
Okay, I'll check what I can do with this.  But I don’t see a problem in this, because I don’t know cases when you need to use a route indicator  with a repeater route

**Comment by LennDoMations** [comment]
> > When you have a routnumber in your signal and an active repeater route it should disable occupation check all the time
> 
> why would you use a route pointer and a repeater route at the same time?

I mean route number. Not route indicator. If I have a route number in the signal like 1 or 2 and the repeater route is active it will disable occupation check. But when I also have pass occupation Signal checked it overwrites that.

**Comment by alexandr-sizov** [comment]
Oh, ok. But i still do not understand how it can be in a repeater. If you use repeater, you must't use other route types besides repeater. In this case previous signals not see this signal and routenumber field becomes useless.

**Comment by alexandr-sizov** [comment]
And i check repeater behaviour, i remember it stop check occupation regardless from routenumber but always.

**Comment by alexandr-sizov** [comment]
8:57] Αλέξανδρος: Hi
[8:57] Αλέξανδρος: Слушай, я тут по одному issue посмотрел код сигналки
[8:57] Αλέξανδρος: Ядра
[8:57] Αλέξανδρος: Функция скантрек
[8:58] Αλέξανδρος:
```isolating = ((v.TrackDir == dir and not v.Routes[v.Route or 1].Repeater) or (v.TrackDir == dir and v.Routes[v.Route or 1].Repeater and tonumber(v.RouteNumber) == 9) or (tonumber(v.RouteNumber) ~= nil and v.Routes[v.Route or 1].Repeater)) and not v.PassOcc```
[8:58] Αλέξανδρος: Не подскажешь что тут за шаманство с репитерами?
[9:00] Αλέξανδρος: Человек нарвался на проблему, что если в сигнале прописан роут намберр и маршрут у него сейчас репитер, то репитер изолирует участок. В душе не знаю где такое получается, но тем не менее это странно 
[9:01] Αλέξανδρος: Тут какой то странный шайтан с роутнамберами, заложенный явно специально 
[9:02] Αλέξανδρος: Честно говоря, вроде вырезать можно, но я пока не понимаю что может пойти не так
[15:39] glebqip: Это костыль, дикий костыль
[15:39] glebqip: Используемый костыль
[15:41] glebqip: Я не знаю почему и зачем это я сделал именно так, но была вот проблема когда на съездах например соседний путь давал занятость
[15:41] glebqip: В сигналку можно добавить проверку думаю, что если нет авто маршрутов то такой фкнкционал

**Comment by alexandr-sizov** [comment]
Don't use a route number in a signal that has repeater routes.

**Comment by LennDoMations** [comment]
> And i check repeater behaviour, i remember it stop check occupation regardless from routenumber but always.

No it doesnt

**Comment by LennDoMations** [comment]
> Don't use a route number in a signal that has repeater routes.

I do because it is needed to disable occupation check. at least in the current metrostroi.
this :

isolating = ((v.TrackDir == dir and not v.Routes[v.Route or 1].Repeater) or (v.TrackDir == dir and v.Routes[v.Route or 1].Repeater and tonumber(v.RouteNumber) == 9) or (tonumber(v.RouteNumber) ~= nil and v.Routes[v.Route or 1].Repeater)) and not v.PassOcc

should be this:

isolating = ((v.TrackDir == dir and not v.Routes[v.Route or 1].Repeater) or (v.TrackDir == dir and v.Routes[v.Route or 1].Repeater and tonumber(v.RouteNumber) == 9) or (tonumber(v.RouteNumber) ~= nil and v.Routes[v.Route or 1].Repeater))

**Comment by LennDoMations** [comment]
This would ignore the passocc for repeaters what disable occupation check because repeaters should ALWAYS block occupation check when they have a route number. or just add another checkbox "disable occupation check with repeater routes"

**Comment by LennDoMations** [comment]
@alexandr-sizov

**Comment by alexandr-sizov** [comment]
Again. This code will not change, since the consequences are not clear for existing signals. I will not add another incomprehensible checkbox. I have already said that I do not know of cases where this behavior is a problem. If you specify a routenumber in a signal that is a repeater, you are doing something wrong and wrong.
