### ISSUE TITLE
Кривое освещение приборной панели на 81-717

### ISSUE THREAD

**Issue by Maks-gaming** [metrostroi-repo/MetrostroiAddon#489]
Кривой свет приборов 81-717

**Как воспроизвести:**
1. Спавн состава 81-717 
2. Нажмите на вкл света приборов
3. Получите ошибку

**Скриншот**
![image](https://user-images.githubusercontent.com/77161824/166095755-bef046d1-bd66-4c71-b756-ae263620d453.png)

**Информация об игре**
 - Версия Garry's mod: x64+chromium
 - Где происходит ошибка: локальня игра
 - Наличие пользовательских модов метростроя: нет
 - Операционная система: Windows

**Comment by CrIcKeT98** [comment]
Не баг. Источник света намеренно не кастует тени. Исправляется галкой "Вкл. тени от остальных источников света" в Q->Утилиты->Клиент.
