### ISSUE TITLE
Выбивает А54 при выключенной батареи.

### ISSUE THREAD

**Issue by NikPatry** [metrostroi-repo/MetrostroiAddon#496]
**Выбивает А54 при выключенной Батареи**

Как воспроизвести
1. Спавн состава 81-717,81-717.5 МСК (ЛВЗ,МВМ)
2. Выберите Состояние "Депо" либо же просто выключите Батарею.
3. Переведите реверсивную рукоятку вперед в двух кабинах
4. Получите Выбитый автомат А54 Управление Поездом(при ВЫКЛЮЧЕННОЙ батареи)

**Информация об игре**
 - Версия Garry's mod: chromium
 - Где происходит ошибка: локальная игра
 - Наличие пользовательских модов метростроя: есть/нет
 - Операционная система: Windows

**Comment by BlueSnooty** [comment]
Пофиксил и создал пулл-реквест

**Comment by BlueSnooty** [comment]
Хотя, кажется, я поторопился. Возможно, теперь появится другой баг, связанный с КРУ >_>
