### ISSUE TITLE
Спавнится с другой маской (81-717)

### ISSUE THREAD

**Issue by EgorTresh** [metrostroi-repo/MetrostroiAddon#501]
При спавне состава 81-717 при выбранной маске 1-4-1 спавнится состав с маской 2-2-2

**Как воспроизвести:**
1. Спавн состава 81-717 (МВМ) с маской 1-4-1
![изображение](https://user-images.githubusercontent.com/62115315/171695287-50d526ba-57fc-43fe-b5c5-8f6d2d1aee03.png)
2. Получите ошибку

Что должно быть:
Головной вагон 81-717 с маской 1-4-1

Консоль:
![изображение](https://user-images.githubusercontent.com/62115315/171695163-9d3c2980-9150-405d-8a46-e5f4b6f09d78.png)

**Информация об игре**
 - Версия Garry's mod: chromium
 - Где происходит ошибка: локальная игра
 - Наличие пользовательских модов метростроя: есть
 - Операционная система: Windows 11

**Comment by Hellss** [comment]
![image](https://user-images.githubusercontent.com/16958912/171958709-282798eb-4531-49eb-ba33-071ecc8e3126.png)
на гитхаб версии нет маски 1-4-1, только 1-4-1 (М)

**Comment by CrIcKeT98** [comment]
Не воспроизводится.
Похоже на устаревшую версию обновления, на текущий момент этой маски нет.
