### ISSUE TITLE
Сломанные звуки номерного (BASS_ERROR_FILEFORM)

### ISSUE THREAD

**Issue by Enalian** [metrostroi-repo/MetrostroiAddon#508]
**Пожалуйста, опишите найденную вами ошибку**
Сломанные звуки номерного. ErrCode: 41, ErrName: BASS_ERROR_FILEFORM.

**Как воспроизвести:**
Пошагово, как нам повторить эту ошибку у себя.
Пример:
1. Спавн состава 81-717 (МВМ)
2. Запустить и поехать
3. Услышать ломанные звуки (если вообще услышать)

**Вывод консоли**
Sound:subway_trains/common/other/radio/vpr_start.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/other/radio/vpr_off.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/junk/junk_background3.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/10_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/40_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/70_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/80_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/rolling_outside_low.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/rolling_outside_medium2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/pneumatic/release_0.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_start2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_loop2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rk/rk_spin.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/junk/junk_background3.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/10_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/40_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/70_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/80_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/rolling_outside_low.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/rolling_outside_medium2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/pneumatic/release_0.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_start2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_loop2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_stop2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rk/rk_start.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rk/rk_spin.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/bpsn/bpsn_olow.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/junk/junk_background3.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/10_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/40_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/70_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/80_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/rolling_outside_low.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/rolling_outside_medium2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/pneumatic/release_0.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_start2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_loop2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_stop2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rk/rk_start.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rk/rk_spin.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/bpsn/bpsn_nnov.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/junk/junk_background3.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/10_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/40_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/70_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/80_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/rolling_outside_low.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/rolling_outside_medium2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/pneumatic/release_0.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_start2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_loop2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_stop2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rk/rk_start.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rk/rk_spin.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/bpsn/old.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/junk/junk_background3.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/10_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/40_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/70_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/80_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/rolling_outside_low.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/rolling_outside_medium2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/pneumatic/release_0.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_start2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_loop2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_stop2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rk/rk_start.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rk/rk_spin.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/other/radio/vpr_start.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/other/radio/vpr_off.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/door/door_roll.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/junk/junk_background3.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/10_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/40_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/70_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/80_rolling.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/rolling_outside_low.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rolling/rolling_outside_medium2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/pneumatic/release_0.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_start2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_loop2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/compressor/compressor_717_stop2.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rk/rk_start.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/rk/rk_spin.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/bpsn/old.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/other/radio/vpr_loop.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/bpsn/bpsn_spb.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/717/bpsn/bpsn_spb.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,
Sound:subway_trains/common/other/radio/vpr_loop.wav
	ErrCode:41, ErrName:BASS_ERROR_FILEFORM,

**Скриншот вывода консоли**
Не могу скрин приложить, т.к. осталась только копия вывода

**Информация об игре**
 - Версия Garry's mod: обычная и x64 (на остальных не тестил)
 - Где происходит ошибка: сервер (локальный)/локальная игра
 - Наличие пользовательских модов метростроя: есть
 - Операционная система: Windows 11

**Comment by KimChinUkr** [comment]
I completely agree with this issue!

**Comment by kosmik641** [comment]
Если распаковать звуки из GMA, проблема остается?

**Comment by Enalian** [comment]
Да, все тоже самое

**Comment by CrIcKeT98** [comment]
Невозможно исправить, особенность гмода.
