### ISSUE TITLE
Баг пневматики промежутка

### ISSUE THREAD

**Issue by ImPerzz** [metrostroi-repo/MetrostroiAddon#512]
[MetrostroiAddon] lua/metrostroi/systems/sys_81_717_pneumatic.lua:403: attempt to index field 'EPKC' (a nil value)
  1. Think - lua/metrostroi/systems/sys_81_717_pneumatic.lua:403
   2. Think - lua/entities/gmod_subway_base/init.lua:1770
    3. unknown - lua/entities/gmod_subway_81-714_mvm/init.lua:308

**Comment by BlueSnooty** [comment]
Готово
