### ISSUE TITLE
Баг с дверьми по мфду

### ISSUE THREAD

**Issue by Hellss** [metrostroi-repo/MetrostroiAddon#520]
Противоориентированные вагоны на 720,722 показывают двери не в правильном порядке 
![image](https://user-images.githubusercontent.com/16958912/179692891-559cb611-9336-4072-88cf-4bb224ed7554.png)

По идее должно быть так:
Train:SetNW2Bool("VityazDoor"..d.."L"..i,train["Door"..(orientation and d or 9-d).."Closed"])
Train:SetNW2Bool("VityazDoor"..d.."R"..i,train["Door"..(orientation and d+4 or 5-d).."Closed"])

**Comment by fixinit75** [comment]
Не воспроизводится. В какой ситуации оно показывает двери в неправильном порядке?

**Comment by Hellss** [comment]
Ну в противоориентированных вагонах двери не в том порядке идут (лучше 2 створки какие то скриптово открыть, видно будет)

**Comment by fixinit75** [comment]
Да, действительно, вижу
