### ISSUE TITLE
Не снимается напряжение с состава при отжатии ТКПР и metrostroi_train_requirethirdrail 0

### ISSUE THREAD

**Issue by fixinit75** [metrostroi-repo/MetrostroiAddon#523]
![image](https://user-images.githubusercontent.com/78933401/180005002-66320c01-35e9-4c50-8130-20ee0bd007ce.png)
Отжаты на всех вагонах, напряжение имеется
![image](https://user-images.githubusercontent.com/78933401/180005095-a544fe77-2145-4f15-beaa-a17fc0156406.png)
Значение переменной
![image](https://user-images.githubusercontent.com/78933401/180005332-6b09d6b3-e547-4b3a-b5c2-7906804f0bb4.png)

**Comment by BlueSnooty** [comment]
А почему оно должно сниматься? Ведь логично, что эта переменная делает так, чтобы напряжение было всегда и везде

**Comment by fixinit75** [comment]
Потому что когда отжимаешь токоприемники, ожидаешь именно это, даже если эта переменная является ложью
