### ISSUE TITLE
Бесконечно появляются пассажиры

### ISSUE THREAD

**Issue by ImPerzz** [metrostroi-repo/MetrostroiAddon#535]
metrostroi_time_old 1
metrostroi_passengers_scale 30 (ранее стоял 100)
На некоторых станциях пассажиры появляются до бесконечности после того как все сели в поезд
Последний раз помню Хелл что-то с ними делал по-этому на него кидаю :D

https://user-images.githubusercontent.com/24627327/182939218-a468559f-1739-4edb-8c6d-d06cbd3ccd0a.mp4

**Comment by Hellss** [comment]
не повторяется чет
