### ISSUE TITLE
Длинная дырка на раме окна на промежуточном вагоне 81-714

### ISSUE THREAD

**Issue by Alexrig23** [metrostroi-repo/MetrostroiAddon#553]
![Снимок экрана (2706)](https://user-images.githubusercontent.com/80965105/187251412-599be3fe-7b73-410a-a9c0-fbbfa74d8fb2.png)

Салон насквозь видно.

**Comment by CrIcKeT98** [comment]
Никакой дыры нет
![image](https://user-images.githubusercontent.com/33666353/187403403-609069fc-bb60-45e4-845f-067beaab9ecf.png)
