### ISSUE TITLE
Состав сгорает после постановки ручки в ход (720.1)

### ISSUE THREAD

**Issue by EgorTresh** [metrostroi-repo/MetrostroiAddon#564]
При постановке КМ в положение ход-4 сразу же сгорает состав

1. Спавн состава 81-720.1 (Яуза)
2. Реверс вперед
3. КМ в Ход-4
4. Получите ошибку
(видео ошибки - https://youtu.be/RKDdRlmbE1Y)

**Вывод консоли**
ServerLog: [ULX] kalthoff_<STEAM_0:1:156729591> used the tool train_spawner on maps/gm_nizninovgorod_line_2.bsp
ServerLog: [ULX] Игрок kalthoff_ заспавнил 5 вагонов 81-720.1 (Яуза).
Местоположение: перегон.
Assigned number 00033 to gmod_subway_81-720_1(0138 81-720_1)
Assigned number 00141 to gmod_subway_81-721_1(0148 81-720)
Assigned number 00140 to gmod_subway_81-721_1(0154 81-720)
Assigned number 00149 to gmod_subway_81-721_1(0160 81-720)
Assigned number 00031 to gmod_subway_81-720_1(0166 81-720_1)
kalthoff_<STEAM_0:1:156729591> used the tool train_spawner on maps/gm_nizninovgorod_line_2.bsp
Игрок kalthoff_ заспавнил 5 вагонов 81-720.1 (Яуза).Местоположение: перегон.
You're playing on Garry's Mod, enjoy your stay!
Announcer error in message click1
Announcer error in message click2
Removed number 00033 to gmod_subway_81-720_1(0138 81-720_1)
Removed number 00141 to gmod_subway_81-721_1(0148 81-720)
Removed number 00140 to gmod_subway_81-721_1(0154 81-720)
Removed number 00149 to gmod_subway_81-721_1(0160 81-720)
Removed number 00031 to gmod_subway_81-720_1(0166 81-720_1)

**Скриншот вывода консоли**
![изображение](https://user-images.githubusercontent.com/62115315/198580970-ca2702a5-ead2-4a18-8cd7-a022c41cd47d.png)

**Информация об игре**
 - Версия Garry's mod: chromium
 - Где происходит ошибка: локальная игра
 - Наличие пользовательских модов метростроя: есть
 - Операционная система: Windows 11

**Comment by toxin1pilot** [comment]
Вагоны стороннего дополнения, обращайтесь к их автору.

**Comment by toxin1pilot** [comment]
Состав является независимым дополнением и не относится к оригинальному дополнению метростроя. Свяжитесь с авторами данного дополнения
