### ISSUE TITLE
Состав не сцепляется сам при спавне

### ISSUE THREAD

**Issue by EgorTresh** [metrostroi-repo/MetrostroiAddon#565]
Заспавнить любой состав и с большой вероятностью он не сцепится сам

**Как воспроизвести:**
1. Спавн состава
2. Получите ошибку
(видео ошибки - https://youtu.be/iwPsBO2pync)

ServerLog: [ULX] kalthoff_<STEAM_0:1:156729591> used the tool train_spawner on maps/gm_nizninovgorod_line_2.bsp
ServerLog: [ULX] Игрок kalthoff_ заспавнил 5 вагонов 81-760 (Ока).
Местоположение: перегон.
Assigned number 37141 to gmod_subway_81-760(0129 81-760)
Assigned number 30294 to gmod_subway_81-761(0139 81-760)
Assigned number 30478 to gmod_subway_81-761(0145 81-760)
Assigned number 30285 to gmod_subway_81-761(0151 81-760)
Assigned number 37096 to gmod_subway_81-760(0157 81-760)
kalthoff_<STEAM_0:1:156729591> used the tool train_spawner on maps/gm_nizninovgorod_line_2.bsp

[metrostroiaddon-dev] addons/metrostroiaddon-dev/lua/entities/gmod_train_bogey/cl_init.lua:227: attempt to compare nil with number

![изображение](https://user-images.githubusercontent.com/62115315/198582109-8aeb980a-8b5e-491a-a5c9-7e4fad748a4f.png)

**Информация об игре**
 - Версия Garry's mod: chromium
 - Где происходит ошибка: локальная игра
 - Наличие пользовательских модов метростроя: есть
 - Операционная система: Windows 11

**Comment by toxin1pilot** [comment]
А на вагонах, встроенных в метрострой, это проявляется? 760 всё-же отдельное дополнение

**Comment by EgorTresh** [comment]
> А на вагонах, встроенных в метрострой, это проявляется? 760 всё-же отдельное дополнение

Да, проявляется

**Comment by fixinit75** [comment]
А, это чёртова физика сурса на 64-битных бетах, пробовал решить это, но не получилось

**Comment by kosmik641** [comment]
Судя по всему, используется 64-битный клиент, физика там поломана, с метростроем не связана
