### ISSUE TITLE
При разряженной ТМ (не от крана машиниста) ~3,5 Ат, нет давления в ТЦ

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#58]

**Comment by CrIcKeT98** [comment]
Какой кран машиниста?

**Comment by CrIcKeT98** [comment]
Проверил на 81-717 МВМ с 013 и 334 краном. Давление в ТЦ зависит от давления в ТМ, на головных и промежуточных вагонах все в порядке, проблем не выявил.
