### ISSUE TITLE
ПА: Звук кнопок

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#60]

**Comment by kosmik641** [comment]
Звук кнопок включается/выключается зажатию кнопки F. Может по дефолту сделать звук включенным?

https://user-images.githubusercontent.com/70780122/125305491-0a460700-e337-11eb-9c3b-c9dd10c917b0.mp4

**Comment by glebqip** [comment]
Вероятно тут был именно этот функционал. Идея сделать включенным(если он щас выкл) правильная, но он и в воркшопе вроде щас есть

**Comment by kosmik641** [comment]
В воркшопе такой функционал отсутствует
