### ISSUE TITLE
Промежуток из 508Т

### ISSUE THREAD

**Issue by CrIcKeT98** [metrostroi-repo/MetrostroiAddon#65]

**Comment by cyber-dream** [comment]
@glebqip что здесь конкретно требуется?

**Comment by MrSandManFM** [comment]
Вероятно имелось ввиду это:
![image](https://user-images.githubusercontent.com/4011223/107233051-33cecf80-6a33-11eb-8b49-cfdaf60e9f86.png)

**Comment by Alexrig23** [comment]
Еж3РУ1 уже для Метростроя делают
