### ISSUE TITLE
Неточности работы 717 ЛВЗ

### ISSUE THREAD

**Issue by CrIcKeT98** [metrostroi-repo/MetrostroiAddon#73]
"А43 сработка ЭПК будет
А42 вообще отвечает за ПБ/КБ при его отключении они просто не работают, ЭПК не срабатывает
А48 ЭПК срабатывает на экране пишет Установи РР
С выкл ВАУ можно запустить аппаратуру и перейти в рабочий режим, все тесты НОРМА
Но
Будут висеть 2е вентиля
При нажатии на ПБ 2е отпускают, остаются 1е
Как в режиме ОС"

**Comment by alexandr-sizov** [comment]
#353
