### ISSUE TITLE
Если не найден материал для скина состава - не выводится ошибка, просто грузится стоковая текстура

### ISSUE THREAD

**Issue by cyber-dream** [metrostroi-repo/MetrostroiAddon#91]
Мне кажется, это немного неявное поведение и стоит вывести конкретную ошибку в консоль

**Comment by ImPerzz** [comment]
Добавил вывод ошибки в косноль.
Эмо-текстуры нет смысла делать, есть игроки я в их числе которые некоторые скины не ставят из за их ущербности и из-за нежелания на них смотреть, молчу про то что бы поставить.
