### ISSUE TITLE
Не влезает весь текст в экран АСНП Еж3

### ISSUE THREAD

**Issue by toxin1pilot** [metrostroi-repo/MetrostroiAddon#94]
![20210106165746_1](https://user-images.githubusercontent.com/14408597/103776410-740bee00-5040-11eb-9761-e38cd8e05678.jpg)

**Comment by ImPerzz** [comment]
В реальности дисплей АСНП на ежах и на номерах был один и тот же по размерам.
Я думаю это вопрос к модели, на таком дисплее нереально уместить понятную информацию, либо делать как в реале.
Жду мнения других, как лучше поступить
